.github/PULL_REQUEST_TEMPLATE.md
README.md

- Closes #50 
- Update PR template
- Improve repo README
_This PR template style was inspired
by [ionic-framework](https://github.com/ionic-team/ionic-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md)._

Contributors guide improvements

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Contributors Guidelines

---

app/src/main/java/com/ivy/wallet/ui/home/HomeMoreMenu.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt

- Closes #18 
- Swipe Down listener for HomeTab
- Swipe Up listener for HomeMoreMenu
Special thanks to @timmyCoder for the contribution with this simple solution!

Open/Close Home More Menu with gesture

---

README.md

Include Design section

---

app/src/main/java/com/ivy/wallet/logic/csv/CSVImporter.kt
app/src/main/java/com/ivy/wallet/logic/csv/CSVMapper.kt
app/src/main/java/com/ivy/wallet/logic/csv/model/RowMapping.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/DefaultImportSteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/FortuneCitySteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/IvyWalletSteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/KTWMoneyMangerSteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/MoneyManagerPraseSteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/OneMoneySteps.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/WalletByBudgetBakersSteps.kt

- Closes #69 
- Finish import CSV from Fortune City

Import fortune city

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

Bump version

---

app/src/main/java/com/ivy/wallet/Constants.kt
app/src/main/java/com/ivy/wallet/ui/IvyContext.kt
app/src/main/java/com/ivy/wallet/ui/IvyViewModel.kt
app/src/main/java/com/ivy/wallet/ui/accounts/AccountsViewModel.kt
app/src/main/java/com/ivy/wallet/ui/balance/BalanceScreen.kt
app/src/main/java/com/ivy/wallet/ui/balance/BalanceViewModel.kt
app/src/main/java/com/ivy/wallet/ui/budget/BudgetScreen.kt
app/src/main/java/com/ivy/wallet/ui/budget/BudgetViewModel.kt
app/src/main/java/com/ivy/wallet/ui/category/CategoriesViewModel.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeHeader.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt
app/src/main/java/com/ivy/wallet/ui/reports/FilterOverlay.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportViewModel.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/ChoosePeriodModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/model/Month.kt
app/src/main/java/com/ivy/wallet/ui/theme/wallet/PeriodSelector.kt

- Closes #82 
- Everything regarding start day of month
- IvyContext#selectedPeriod
- IvyContext#startDayOfMonth

Start date 28 next month

---

app/src/main/java/com/ivy/wallet/Constants.kt
app/src/main/java/com/ivy/wallet/ui/IvyContext.kt
app/src/main/java/com/ivy/wallet/ui/IvyViewModel.kt
app/src/main/java/com/ivy/wallet/ui/accounts/AccountsViewModel.kt
app/src/main/java/com/ivy/wallet/ui/balance/BalanceScreen.kt
app/src/main/java/com/ivy/wallet/ui/balance/BalanceViewModel.kt
app/src/main/java/com/ivy/wallet/ui/budget/BudgetScreen.kt
app/src/main/java/com/ivy/wallet/ui/budget/BudgetViewModel.kt
app/src/main/java/com/ivy/wallet/ui/category/CategoriesViewModel.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeHeader.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt
app/src/main/java/com/ivy/wallet/ui/reports/FilterOverlay.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportViewModel.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/ChoosePeriodModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/model/Month.kt
app/src/main/java/com/ivy/wallet/ui/theme/wallet/PeriodSelector.kt

- Closes #82 
- Everything regarding start day of month
- IvyContext#selectedPeriod
- IvyContext#startDayOfMonth

Closes #82

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt
fastlane/Fastfile
fastlane/metadata/android/en-GB/changelogs/default.txt

Bugfix release

---

.github/workflows/internal_release.yml
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt
fastlane/Fastfile

Fix Fastfile and bump version

---

.github/ISSUE_TEMPLATE/feature-request.md
app/build.gradle.kts
app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/logic/csv/CSVImporter.kt
app/src/main/java/com/ivy/wallet/ui/theme/components/IvyButton.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/HistoryDateDivider.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt
app/src/main/java/com/ivy/wallet/ui/webView/WebViewScreen.kt
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

- Closes #96 
- Closes #96 
- Closes #5 
- More compact transactions
- Fixed import CSV from Fortune City
- Display transaction's year if the date isn't in the current year
- Support Dark Mode in WebView

Bugfixes and quick improvements

---

.github/ISSUE_TEMPLATE/feature-request.md
app/build.gradle.kts
app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/logic/csv/CSVImporter.kt
app/src/main/java/com/ivy/wallet/ui/theme/components/IvyButton.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/HistoryDateDivider.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt
app/src/main/java/com/ivy/wallet/ui/webView/WebViewScreen.kt
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

- Closes #96 
- Closes #96 
- Closes #5 
- More compact transactions
- Fixed import CSV from Fortune City
- Display transaction's year if the date isn't in the current year
- Support Dark Mode in WebView
- Update "Request a feature" template

Bugfixes and improvements

---

app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/logic/csv/CSVImporter.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

- Fortune City CSV import
- Display selected period more properly when the start date of the month isn't set to 1

Minor bugfixes and improvments

---

app/src/main/java/com/ivy/wallet/Constants.kt
app/src/main/java/com/ivy/wallet/ui/IvyActivity.kt
app/src/main/java/com/ivy/wallet/ui/IvyContext.kt
app/src/main/java/com/ivy/wallet/ui/IvyViewModel.kt
app/src/main/java/com/ivy/wallet/ui/Screens.kt

- Closes #107
- With this commit Users with "App Lock Enabled" gets their Ivy wallet preview hidden in recent menu (Users can still take screenshot within the app)
- After 5 Mins of inactivity the users are prompted to re-authenticate
This commit includes code improvements which are
- New Screen is added to Screen class
- authenticateWithOSBiometricsModal() functional changes
- handleBiometricAuthenticationResult() changes
- UserInactivity is now managed via Ivy …

Hide preview in Recent Apps & ReAuthenticate on UserInactivity

---

app/src/main/java/com/ivy/wallet/Constants.kt
app/src/main/java/com/ivy/wallet/base/MVVMExt.kt
app/src/main/java/com/ivy/wallet/persistence/SharedPrefs.kt
app/src/main/java/com/ivy/wallet/ui/IvyActivity.kt
app/src/main/java/com/ivy/wallet/ui/IvyContext.kt
app/src/main/java/com/ivy/wallet/ui/IvyViewModel.kt
app/src/main/java/com/ivy/wallet/ui/Screens.kt
app/src/main/java/com/ivy/wallet/ui/applocked/AppLockedScreen.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt

- Rework "App Lock" mechanism
- Refactoring
- Introduce `Flow` API

Proper "App Lock" mechanism + refactoring

---

app/src/main/java/com/ivy/wallet/ui/IvyViewModel.kt

Fix critical onboarding black screen bug

---

app/src/main/java/com/ivy/wallet/ui/theme/modal/BudgetModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/BufferModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AccountModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AmountModal.kt
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

- Closes #135 
- Closes #136 
-
-
-

Amount cannot be set bugfix

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

- Updated RecyclerView Library from 1.2.0 -> 1.2.1

RecyclerView Library Update

---

app/src/main/java/com/ivy/wallet/base/ActivityResultExt.kt
app/src/main/java/com/ivy/wallet/logic/CustomerJourneyLogic.kt
app/src/main/java/com/ivy/wallet/ui/IvyActivity.kt
app/src/main/java/com/ivy/wallet/ui/IvyContext.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsScreen.kt

Code improvements

---

app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt

successfully.
- Right click
_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._
**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`
**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle …

Added Swipe to Change Month in ItemStatisticScreen

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

successfully.
- Right click
_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._
**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`
**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle …

Change version name

---

app/src/main/java/com/ivy/wallet/ui/balance/BalanceViewModel.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/model/Month.kt

successfully.
- Closes #358 
- a increment/decrement now takes "year" into its consideration 
- b
- c
- d
**Method …

Bug-Fix #358 : Fixed Previous month transactions disappearing

---

app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/LoanRecordModal.kt

successfully.
- Closes #357, #174 
- The Timezone error was occurring because time was returned in UTC format and date in LocalTimeZone hence combining them would have edge case errors. To fix it convert both to local add and convert back to UTC.
- Pixel 5 API …

Bug-Fix #357: Timezone error fixed

---

app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt

successfully.
- Closes #416
- a Transactions are now searched with Time in UTC
- b
- c
- d …

Fix issue 416 : Fixed Transactions occurring out of its scope 

---

app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt

successfully.
- Closes #400
- a Fixed Disappearing January transactions due to year change 
- b Fixed month calculations for startDayOfTheMonth != 1
For eg: Consider start day of month =29
Before Bug Fix
Dec 29th - Jan 28th --> 1 Month
Jan 29th - Feb 27th --> 1 Month
Feb 28th - March 27th …

Bug-Fix #400: Fixed 'Start date of month != 1 is broken for January'

---

app/src/androidTest/java/com/ivy/wallet/compose/scenario/OperationsCoreTest.kt
app/src/main/java/com/ivy/wallet/base/DateExt.kt
app/src/main/java/com/ivy/wallet/ui/balance/BalanceViewModel.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/model/TimePeriod.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/ChoosePeriodModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/LoanRecordModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/model/Month.kt
buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

successfully.
- a
- b
- c
- d
- Find `com …

Date bugfixes and improvements

---

app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt

successfully.
- a Opening and closing of more menu is now easier and can be opened from anywhere in the home screen via a swipe down previously it was possible only on swiping down from income & expanse part
- b
- c
- d
- …

Improvement: MoreMenu opening/closing

---

app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionViewModel.kt

successfully.
- Closes #513 
- Right click
- `Run …

Fix Broken Account Transfer

---

app/src/main/java/com/ivy/wallet/functional/wallet/WalletCore.kt

successfully.
- Closes #530 
- a
- b
- c
- d
- …

BugFix: Broken Amount Calculation

---

app/src/main/java/com/ivy/wallet/ui/loan/LoanViewModel.kt
app/src/main/java/com/ivy/wallet/ui/loan/LoansScreen.kt
app/src/main/java/com/ivy/wallet/ui/loan/data/DisplayLoan.kt

successfully.
- a Introduced new Classes Called LoanScreenState and LoanScreenEvent where state represents the data displayed by the 
UI at any given point of time, where as LoanScreenEvent describes all the UI events that the user can interact with …

LoanScreen Refactor

---

app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt

successfully.
- Closes #616 
PS: Lint fails because of AccountModal Test not being updated  the phrase "Include in balance" is not changed to "Include account"
- Large …

Fix-issue-616 Wrong Account Balance

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt
ivy-design/src/main/java/com/ivy/design/api/IvyUI.kt

successfully.
- Closes #91 
- added systemUiController library to control the visibility 
**Method 1: Android Studio …

Bug fix #91: Navigation Buttons aren't visible

---

app/src/main/java/com/ivy/wallet/model/IvyCurrency.kt

successfully.
- Crypto.org Coin ($CRO) is now rebranded as Cronos effective from February 18, 2021. **[Source](https://medium.com/cronos-chain/cro-is-now-cronos-bf103c257bd)**
- …

Support $CRO Crypto Rebranding

---

app/src/androidTest/java/com/ivy/wallet/compose/helpers/AccountModal.kt
app/src/main/java/com/ivy/wallet/di/AppModule.kt
app/src/main/java/com/ivy/wallet/logic/csv/model/ImportType.kt
app/src/main/java/com/ivy/wallet/logic/zip/ExportZipLogic.kt
app/src/main/java/com/ivy/wallet/logic/zip/ZipUtils.kt
app/src/main/java/com/ivy/wallet/logic/zip/model/IvyWalletCompleteData.kt
app/src/main/java/com/ivy/wallet/persistence/dao/AccountDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/BudgetDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/CategoryDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/LoanDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/PlannedPaymentRuleDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/SettingsDao.kt
app/src/main/java/com/ivy/wallet/persistence/dao/TransactionDao.kt
app/src/main/java/com/ivy/wallet/ui/IvyActivity.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/ImportScreen.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/ImportViewModel.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/ImportInstructions.kt
app/src/main/java/com/ivy/wallet/ui/csvimport/flow/instructions/IvyWalletSteps.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/loandetails/LoanDetailsScreen.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsScreen.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/ProgressModal.kt

successfully.
- Closes #521 
- a Added Zip + Json Exports i.e. Data to be exported is now saved in JSON & not CSV
- b Accommodates only Import of old csv files and new backups will now be in Zip + Json 
PS: Json exports are easier to create and will accommodate new changes unlike csv where …

Added Zip Exports

---

.github/PULL_REQUEST_TEMPLATE.md

successfully.
- Deleted Duplicate Line in PR Template …

Deleted Duplicate Line in PR Template

---

app/src/main/java/com/ivy/wallet/base/AmountFormatting.kt
app/src/main/java/com/ivy/wallet/model/CustomExchangeRateState.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionViewModel.kt
app/src/main/java/com/ivy/wallet/ui/edit/core/EditBottomSheet.kt
app/src/main/java/com/ivy/wallet/ui/theme/components/CustomExchangeRateCard.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AmountModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt

successfully.
- Closes #582 
- a Ability to set custom Exchange rate and now exchanged rate is displayed in transaction cards
- b Custom Exchange Rate is can be set only up to 4 decimal points 
[---]
- Pixel 3XL API …

Added CustomExchangeRate

---

app/src/main/java/com/ivy/wallet/ui/home/HomeMoreMenu.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/res/drawable/home_more_menu_auto_mode.xml
ivy-design/src/main/java/com/ivy/design/api/IvyDesign.kt
ivy-design/src/main/java/com/ivy/design/api/systems/IvyWalletDesign.kt
ivy-design/src/main/java/com/ivy/design/l0_system/IvyTheme.kt
ivy-design/src/main/java/com/ivy/design/l0_system/Theme.kt

successfully.
- Closes #602 (type issue number here)
- Added an Auto mode for changing the theme automatically as per default device theme.
- Large screen physical …

Fixed Issue #602:Add auto dark theme

---

app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/components/CustomExchangeRateCard.kt
app/src/main/res/drawable/ic_refresh.xml

successfully.
- a BugFix --> Unable to edit exchange Rate
- b Feature --> Reset Exchange Rate
- c
- d …

ExchangeRate Bugfix & Improvements

---

app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt

successfully.
- Closes #684 (type issue number here)
- Added expense description under title in 
- b
- c
- d
- Find `com (androidTest)` …

Added expense description under title in TransactionCard.kt

---

buildSrc/src/main/java/com/ivy/wallet/buildsrc/dependencies.kt

successfully.
- a
- b
- c
- d
- Right click …

Bump version code

---

app/src/main/java/com/ivy/wallet/domain/IvyWalletCompleteData.kt
app/src/main/java/com/ivy/wallet/domain/logic/zip/ExportZipLogic.kt

successfully.
- a Fixed Inability to import old IvyBackup.zip files
- b
- c
- d
- Find `com …

BugFix-- ImportData

---

app/src/main/java/com/ivy/wallet/domain/data/IvyWalletCompleteData.kt
app/src/main/java/com/ivy/wallet/domain/logic/zip/ExportZipLogic.kt

successfully.
- a Fixes the ability to import data that has been backed up before obfuscation 
- b
- c
- d …

BackupData fix

---

app/src/main/java/com/ivy/wallet/ui/edit/PrimaryAttributeColumn.kt
app/src/main/java/com/ivy/wallet/ui/edit/core/Description.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AccountModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AmountModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/CalculatorModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/CategoryModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/ChooseCategoryModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/DescriptionModal.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/HistoryDateDivider.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionSectionDivider.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/Transactions.kt
app/src/main/java/com/ivy/wallet/ui/theme/wallet/AmountCurrency.kt
app/src/main/res/values/strings.xml

successfully.
- a
- b
- c
- d
- Right click …

Added more strings for ui.theme

---

app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AmountModal.kt

successfully.
- Closes #731
- The order of numbers has changed from the phone pattern to the calculator pattern.

Apply calculator pattern to number order

---

app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionViewModel.kt

successfully.
- a
- b
- c
- d
- Right click …

Todo-Fix: CustomExchangeRate

---

app/src/main/java/com/ivy/wallet/domain/data/IvyWalletCompleteData.kt
app/src/main/java/com/ivy/wallet/domain/deprecated/logic/zip/ExportZipLogic.kt
app/src/main/java/com/ivy/wallet/ui/onboarding/viewmodel/OnboardingViewModel.kt

successfully.
- a
- b
- c
- d
- Right click …

BugFix : Broken IvyImport to Db

---

app/src/main/java/com/ivy/wallet/domain/action/category/CategoryIncomeWithAccountFiltersAct.kt
app/src/main/java/com/ivy/wallet/domain/action/charts/PieChartAct.kt
app/src/main/java/com/ivy/wallet/domain/action/transaction/CalcTrnsIncomeExpenseAct.kt
app/src/main/java/com/ivy/wallet/domain/action/transaction/TrnsWithRangeAndAccFiltersAct.kt
app/src/main/java/com/ivy/wallet/domain/pure/data/IncomeExpenseTransferPair.kt
app/src/main/java/com/ivy/wallet/domain/pure/transaction/WalletValueFunctions.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt

successfully.
- [] Bugfix
- a PieChart Act has been re-written to support FP style
- b PieChart now shows a Temp Category  = "Account Transfers" when Treat Transfers As Income Expense is enabled
- c
- d
- Pixel 3XL API 29+ AVD …

PieChart Improvements

---

app/src/main/java/com/ivy/wallet/domain/deprecated/logic/PlannedPaymentsLogic.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/Transactions.kt

successfully.
- Right click
_Note: If …

Added Skip PlannedPayments Transactions

---

README.md
app/src/main/java/com/ivy/wallet/domain/action/viewmodel/home/DueTrnsInfoAct.kt
app/src/main/java/com/ivy/wallet/utils/DateExt.kt
docs/Developer-Guidelines.md

successfully.
- a
- b
- c
- d
- Right click …

Ivy Dev Guidelines update

---

.github/ISSUE_TEMPLATE/import-csv-request.yml
docs/Developer-Guidelines.md

- Removed a description that was mistakenly added in an issue template
- Used Shields badges that say that feedback and proposals are welcome instead of just text. They link to Telegram community
- Used a heading instead of emphasis

Improve docs

---

app/src/main/java/com/ivy/wallet/domain/pure/transaction/WalletValueFunctions.kt
app/src/main/java/com/ivy/wallet/ui/Screens.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportScreen.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportScreenEvent.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportScreenState.kt
app/src/main/java/com/ivy/wallet/ui/reports/ReportViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt

successfully.
- Improper TransfersIn calculation (Improper conversion to baseCurrency)
- Improper Reports Screen Balance Calculation
- Improper Accounts Data passage when computing balance
- Improper AccountsTransfer Category Balance Calculation
-  AccountsTransferCategory Display is now associated with …

ReportsScreen: Imporvements & BugFixes

---

app/src/main/java/com/ivy/wallet/ui/category/CategoriesScreen.kt
app/src/main/java/com/ivy/wallet/ui/category/CategoriesViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/components/ReorderModal.kt
ivy-fp/src/main/java/com/ivy/fp/action/Composition.kt

successfully.
- Fix improper reordered list return 
- Refactored CategoryScreen 
- Category Screen now uses Actions to calculate balance
- Large screen physical device _(might also …

CategoryScreen Improvements & BugFixes

---

app/src/main/java/com/ivy/wallet/ui/theme/components/ReorderModal.kt

successfully.
- a Fix Returning of empty list when no reorder is done
- b
- c
- d
- Find `com …

BugFix: ReorderModal

---

app/src/main/java/com/ivy/wallet/domain/data/SortOrder.kt
app/src/main/java/com/ivy/wallet/io/persistence/SharedPrefs.kt
app/src/main/java/com/ivy/wallet/ui/category/CategoriesScreen.kt
app/src/main/java/com/ivy/wallet/ui/category/CategoriesViewModel.kt
app/src/main/res/drawable/ic_sort_by_alpha_24.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

successfully.
- Closes #827 
Ability to sort categories based on
a) Order Num (Defualt)
b) Category total balance
c) Expenses
d) Alphabetical   …

Sort by for Categories

---

app/src/main/java/com/ivy/wallet/domain/data/IvyCurrency.kt

successfully.
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues/)**.
- Closes #861
- added new cryptocurrency Tron(TRX)
- Right click …

add Tron(TRX) currency

---

app/src/main/java/com/ivy/wallet/domain/deprecated/logic/PlannedPaymentsLogic.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeEvent.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
app/src/main/java/com/ivy/wallet/ui/home/HomeViewModel.kt
app/src/main/java/com/ivy/wallet/ui/theme/transaction/Transactions.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

successfully.
- Closes #962
- There´s a button in the overdue payments list.
- I clic that button
- A confirmation dialog pops up asking for confirmation
- I confirm the skip action
- All the overdue payments are skipped. …

Skip all overdue

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/ivy/wallet/ui/RootViewModel.kt
app/src/main/res/xml/shortcuts.xml

- Add income
- Add expense
- Add transfer
successfully.
- Closes #462 
- Shortcuts added to the app for add Incomes, Expenses or Transfers
**Method 1: Android Studio …

Added app icon shortcuts

---

docs/Business-Model.md
docs/Developer-Guidelines.md

- Closes #977 
- Fixed typos in Developer-Guidelines and Business-Model
- Proposed better wording in several places
- Updated info about `DataStore` implementation
- Updated link to the `Hall of Fame`

issue-977: fixed typos, proposed better wording

---

app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

successfully.
- [Adjustment of a string to align it with the rest of the UI](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/705db0d5817bb2914be392290db57a70c0c12b4e)
- [Improved Italian translation](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/9e16677b775de3804e288b83382d3eea01ed85dd) …

Strings improvements

---

app/src/main/java/com/ivy/wallet/domain/deprecated/logic/LogoutLogic.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsScreen.kt
app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

successfully.
- [Added the "Switch to offline mode" feature](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/847803cb0ee1ed34982ca4b6d05bc19fc1b926b9)
- Large screen physical …

Added the "Switch to offline mode" feature

---

app/src/main/res/values-ar/strings.xml

successfully.
- a
- b
- c
- d
- Right click …

Translated missing arabic strings.

---

app/src/main/res/values-es/strings.xml

successfully.
- Closes https://github.com/ILIYANGERMANOV/ivy-wallet/issues/996
- a
- b
- c
- d
- …

Translated missing spanish strings

---

app/src/main/res/values-hi/strings.xml

successfully.
- Closes #996 
- Added missing translation for the hindi language
- Right click
- `Run …

Translated missing hindi strings

---

app/src/main/java/com/ivy/wallet/ui/component/transaction/HistoryDateDivider.kt

successfully.
- Closes #1054 (type issue number here)
- change date calculation in `HistoryDateDivider.kt` file.
- calculate dates according to current local time instead of current UTC time in `today` variable.
- Large …

fix mismatch in in day calculation for non UTC timezones

---

app/src/main/java/com/ivy/wallet/domain/action/charts/SubCategoryAct.kt
app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticScreen.kt
app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/CategoryModal.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-kn/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

successfully.
- a Added Translations to new sentences used in subcategories feature 
- b Small bugfix of empty subcategories that were displayed  
- c
- d
- Large screen physical …

Subcategories Translations and BugFix

---

app/src/main/java/com/ivy/wallet/ui/reports/FilterOverlay.kt

successfully.
- a Fixed bug which caused multiple keywords to not be added 
Steps to Reproduce bug
1. Go to Reports -> Filter
2. Add Includes keywords
3. Then add Excludes Keyword
4. Then again try to add includes keyword (won't Work)
- Pixel 5 API 29+ AVD emulator …

BugFix: Unable to Add Mutiple Keywords in ReportFilter

---

app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-kn/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

successfully.
- a
- b
- c
- d
- Right click …

Improvements

---

app-base/src/main/java/com/ivy/base/AmountFormatting.kt
ui-components-old/src/main/java/com/ivy/old/theme/modal/edit/CalculatorModal.kt

Remove multiple decimal points from number entered in calculator modal.
successfully.
- Closes #1121 (type issue number here)
- when user opens calaculator in amount modal, user will no longer be able to enter multiple decimal points in one number. 
- Pixel 3XL API …

fix #1121: remove multiple decimal points from number entered in calculator

---

ui-components-old/src/main/java/com/ivy/old/theme/modal/edit/AmountModal.kt

Do not clear crypto amount if 3+ decimals are entered and backspace is pressed
may fix #636
successfully.
- Closes #636 (type issue number here)
- After user enters crypto with more than 3 decimal places amount in add transactions.
- User can remove only one digit from amount using backspace instead of removing entire amount.
**Connect …

Backspace Removes Entire Balance if 3+ Decimal Places Used

---

README.md

Changed "Lint" to "Test" and "internal_release" to "Build"
successfully.
- a
- b
- c
- d
- Find …

Updated Badges.

---

ui-components-old/src/main/java/com/ivy/old/theme/modal/edit/AmountModal.kt

successfully.
- https://github.com/Ivy-Apps/ivy-wallet/issues/1118

added haptic vibrate feedback

---

core/ui/src/main/java/com/ivy/core/ui/icon/picker/IconPickerIcons.kt

successfully.
- a
- b
- c
- d
- Right click …

WIP: keywords

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/dev-contributor-request.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/import-csv-request.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
common/src/main/java/com/ivy/common/Constants.kt
docs/Developer-Guidelines.md
docs/archive/Business-Model.md
fastlane/metadata/android/en-GB/changelogs/default.txt
temp-network/src/main/java/com/ivy/temp/network/service/GithubService.kt

successfully.
- currently all the links are redirected to the correct repository i.e ILIYANGERMANOV -> Ivy-Apps
- redirects may break over time and confuse the contributors as well
- direct links to the repo fixes above issue
- although this is a GitHub project, redirects are not good for SEO, this can affect users trying to find some help by searching on google

update links to point to Ivy-Apps organisation

---

core/domain/src/main/java/com/ivy/core/domain/action/settings/applocked/AppLockedFlow.kt
core/domain/src/main/java/com/ivy/core/domain/action/settings/applocked/WriteAppLockedAct.kt
core/domain/src/main/java/com/ivy/core/domain/action/settings/balance/HideBalanceFlow.kt
core/persistence/src/main/java/com/ivy/core/persistence/datastore/keys/SettingsKeys.kt
home/tab/src/main/java/com/ivy/home/HomeViewModel.kt
settings/src/main/java/com/ivy/settings/SettingsEvent.kt
settings/src/main/java/com/ivy/settings/SettingsScreen.kt
settings/src/main/java/com/ivy/settings/SettingsState.kt
settings/src/main/java/com/ivy/settings/SettingsViewModel.kt

successfully.
- a
- b
- c
- d
- Right click …

Add settings

---

drive/google-drive/src/main/java/com/ivy/drive/google_drive/drivev2/GoogleDriveService.kt
drive/google-drive/src/main/java/com/ivy/drive/google_drive/drivev2/GoogleDriveServiceImpl.kt

Contains the initial interface and implementation.
Tested in isolation and not yet instantiated anywhere in the app
successfully.
- a
- b
- c
- d
- Large screen physical device _(might …

Google drive module refactoring first draft version.

---

core/domain/src/main/java/com/ivy/core/domain/calculation/account/AccountRawStats.kt

successfully.
- a
- b
- c
- d
- Right click …

Small refactoring in AccountRawStats

---

core/data-model/src/main/java/com/ivy/core/data/common/Types.kt
core/data-model/src/main/java/com/ivy/core/data/common/Value.kt
core/domain/src/main/java/com/ivy/core/domain/calculation/Exchange.kt
core/domain/src/main/java/com/ivy/core/domain/calculation/RawStats.kt
core/domain/src/test/java/com/ivy/core/domain/calculation/ArbUtil.kt
core/domain/src/test/java/com/ivy/core/domain/calculation/ExchangeRateUtil.kt
core/domain/src/test/java/com/ivy/core/domain/calculation/ExchangeTest.kt
core/domain/src/test/java/com/ivy/core/domain/calculation/RawStatsTest.kt
core/domain/src/test/java/com/ivy/core/domain/calculation/RawStatsUtil.kt

successfully.
- a
- b
- c
- d
- Right click …

Add `fromX` and `fromXUnsafe` methods for narrowing down types

---

app/src/main/java/com/ivy/wallet/ui/RootActivity.kt
app/src/main/java/com/ivy/wallet/ui/RootEvent.kt
app/src/main/java/com/ivy/wallet/ui/RootViewModel.kt
navigation/src/main/java/com/ivy/navigation/Navigator.kt

- Closes #462 
-  Clicking on shortcuts  navigates the users to the respective screen
- changed the replay to 1 because the observer to it ,in the NavigationRoot is not yet subscribed when the navigate is called.

adding shortcut actions in dev branch

---

.github/ISSUE_TEMPLATE/dev-request.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test.yml

> Upload a screen recording + screenshots to prove that your changes work.
Please check the type of the changes that your PR introduce:
Put an `x` in all the boxes that apply.
- a
- b
- c
- d
_💡 Tip: Attach screenshots and screen recordings. It helps a lot!_
Test your build again with the **app-demo.apk** generated by the `APK workflow`. This is an important step because it applies code obfuscation and R8 that often produces runtime exceptions which make the …

Improve issue templates

---

app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/AmountModal.kt

Please check the type of the changes that your PR introduce:
Old:
New:
<div style="display: flex;">
<div/>
- Closes #2529

Use calculator style number order in AmountKeyboard

---

.github/workflows/upgrade-gradle-wrapper.yml

Fix for upgrade-gradle-wrapper.yml

---

.github/dependabot.yml

> Upload a screen recording + screenshots to prove that your changes work.
Please check the type of the changes that your PR introduce:
Put an `x` in all the boxes that apply.
- a
- b
- c
- d
_💡 Tip: Attach screenshots and screen recordings. It helps a lot!_

Fix dependabot.yml patterns

---

buildSrc/src/main/kotlin/ivy.lint.gradle.kts
config/detekt/baseline.yml
config/detekt/config.yml

[Update detekt config for compose](https://github.com/Ivy-Apps/ivy-wallet/commit/58dc58abd14640c24b64453e8ab2dd7e6bf1c711) 
Updated according to
https://detekt.dev/docs/introduction/compose/

Tune detekt config

---

.github/workflows/apk.yml
.github/workflows/danger_pr.yml
.github/workflows/detekt.yml

- a
- b
- c
- d
_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_
- a
- b
- c
- a
- b
- c

Fix DangerJS failing for external contributors

---

temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt

Flip numpad from:
| 1 | 2 | 3 |
|---|---|---|
| 4 | 5 | 6 |
| 7 | 8 | 9 |
to
| 7 | 8 | 9 |
|---|---|---|
| 4 | 5 | 6 |
| 1 | 2 | 3 |
Doesn't look like.

Flip calculator numpad to a standard layout

---

app/src/main/AndroidManifest.xml
gradle.properties
gradle/libs.versions.toml

- a
- b
- c
- d
_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_
- a
- b
- c
- a
- b
- c

Core api + fix Android BILLING errors

---

screen-home/src/main/java/com/ivy/home/HomeHeader.kt

fixed username text
- a
- b
- c
- a
- b
- c

[#2037] fixed username text

---

config/detekt/baseline.yml
config/detekt/config.yml
ivy-core/src/main/java/com/ivy/core/features/BoolFeature.kt
screen-features/src/main/java/com/ivy/features/FeaturesScreen.kt
screen-features/src/main/java/com/ivy/features/FeaturesUiEvent.kt
screen-features/src/main/java/com/ivy/features/FeaturesUiState.kt
screen-features/src/main/java/com/ivy/features/FeaturesViewModel.kt
screen-settings/src/main/java/com/ivy/settings/SettingsScreen.kt

- a
- b
- c
- d
_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_
- a
- b
- c
- a
- b
- c

Features screen + linters fine-tune

---

screen-contributors/src/main/java/com/ivy/contributors/ContributorsScreen.kt

| Before         | After         |
| -------------- | -------------- |
| ![Before](https://github.com/Ivy-Apps/ivy-wallet/assets/76928501/602c08bf-c3d5-44b6-8180-fb44a2dd6c2f) | ![After](https://github.com/Ivy-Apps/ivy-wallet/assets/76928501/6c4bde9a-d1f1-47b8-b96a-f0b2f377e480) |
Describe things in a short and straightforward manner.
- Currently if a contributor has only 1 contribution the app shows "1 contributions" which is incorrect, this commit fixes that.
- the "Contributors" screen shows "1 contribution" instead of "1 contributions".

Add singular/plural check for ContributorsScreen

---

app/src/main/java/com/ivy/wallet/RootActivity.kt
ivy-design/src/main/java/com/ivy/design/system/IvyMaterial3Preview.kt
ivy-design/src/main/java/com/ivy/design/system/IvyMaterial3Theme.kt
ivy-navigation/src/main/java/com/ivy/navigation/Screen.kt
ivy-navigation/src/main/java/com/ivy/navigation/Screens.kt
temp-old-design/src/main/java/com/ivy/design/api/IvyUI.kt
temp-old-design/src/main/java/com/ivy/design/l0_system/IvyTheme.kt

- a
- b
- c
- d
_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_
- a
- b
- c
- a
- b
- c

M3 theme fixes

---

app/build.gradle.kts
app/src/main/res/resources.properties

- [✅] The PR is submitted to the `main` branch.
- [✅] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [✅] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [✅] My code builds and is tested on a real Android device.
- [✅] I confirm that I've run the code locally and everything works as expected.
Screenshot 1
---
screen recording
---
https://github.com/Ivy-Apps/ivy-wallet/assets/15169545/af1691e0-9b4b-4001-a484-c16535a6465a
- Ability to change the app language through the Android system settings.
_💡 Tip: Please, attach screenshots and screen recordings. …

Added automatic per-app language support

---

ivy-design/build.gradle.kts
screen-attributions/build.gradle.kts
screen-attributions/src/main/java/com/ivy/attributions/AttributionsScreen.kt
screen-contributors/build.gradle.kts
screen-contributors/src/main/java/com/ivy/contributors/ContributorsScreen.kt
screen-features/build.gradle.kts

- New screens now use Material 3 design.
- The old dependencies are removed from their build gradle files
- Closes #2664

Fix issue 2664 - Refactor new screens to use Material 3 design

---

screen-onboarding/src/main/java/com/ivy/onboarding/steps/OnboardingType.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/36114588/54cf39f7-cdac-4640-a2ef-be4205bfe24f
- The onboard screen now scrolls and allows smaller screens to see the entire page
- N/A
- N/A
- Closes #2688

Fix 2688 - Add scroll to OnboardingType composable

---

screen-contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt

- Now the app supports up to 100 contributors showing in Contributors Screen

Support up to 100 contributors showing in Contributors Screen

---

screen-accounts/src/main/java/com/ivy/accounts/AccountState.kt
screen-accounts/src/main/java/com/ivy/accounts/AccountsEvent.kt
screen-accounts/src/main/java/com/ivy/accounts/AccountsState.kt
screen-accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
screen-accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
screen-accounts/src/main/java/com/ivy/accounts/IncomeExpensesRow.kt
screen-main/src/main/java/com/ivy/main/MainScreen.kt

Accounts Screen | Reorder accounts | Account | Edit account | Add new account
---|---|---|---|---
- Accounts Screen is now migrated to ComposeViewModel and our new architecture
- Closes #2700

Fix issue 2700 - Migrate :screen-accounts to ComposeViewModel and our new architecture

---

.idea/.gitignore
screen-search/src/main/java/com/ivy/search/SearchEvent.kt
screen-search/src/main/java/com/ivy/search/SearchScreen.kt
screen-search/src/main/java/com/ivy/search/SearchState.kt
screen-search/src/main/java/com/ivy/search/SearchViewModel.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/132418600/f6c61c0c-fff1-4c90-bee7-2bbfd1fd09ba
- Add SearchState (UiState)
- Add SearchEvent (UiEvent)
- Migrate viewmodel to ComposeViewModel
- a
- b
- c
- a
- b
- c
- Closes #2629

Fix issue #2629: Migrate screen-search to ComposeViewModel

---

app/lint-baseline.xml
screen-home/src/main/java/com/ivy/home/HomeHeader.kt
temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/IvyOutlinedButton.kt

Added min width to button
Check https://github.com/Ivy-Apps/ivy-wallet/issues/2683.
- Closes #2683

Added Min Width to button #2683

---

screen-categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
screen-categories/src/main/java/com/ivy/categories/CategoriesScreenEvent.kt
screen-categories/src/main/java/com/ivy/categories/CategoriesScreenState.kt
screen-categories/src/main/java/com/ivy/categories/CategoriesViewModel.kt

- Migrated the CategoriesViewModel to ComposeViewModel
- Moved CategoriesScreenState and CategoriesScreenEvent to Different Files
https://github.com/Ivy-Apps/ivy-wallet/assets/28820868/a3e7d8e3-31ac-4358-93a6-03767eb5179e
- Closes [https://github.com/Ivy-Apps/ivy-wallet/issues/2622](https://github.com/Ivy-Apps/ivy-wallet/issues/2622)

Migrated viewmodel in screen-categories to ComposeViewModel

---

app/build.gradle.kts
app/src/main/java/com/ivy/wallet/RootActivity.kt
gradle/libs.versions.toml
ivy-resources/src/main/res/values/styles.xml

- Migrated TimePicker to Material M3
- Migrate DatePicker to Material M3
https://github.com/Ivy-Apps/ivy-wallet/assets/103899034/3c86179c-aeb3-4251-bfc0-95b441a0f82e
I have tested the working in all places where there is an option to trigger TimePicker and DatePicker
- None
- None
- Closes #2741

Fix issue #2741

---

.github/PULL_REQUEST_TEMPLATE.md
ivy-design/src/main/java/com/ivy/design/system/IvyMaterial3Theme.kt
ivy-design/src/main/java/com/ivy/design/system/colors/IvyColors.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Update design system colors

---

ivy-data-testing/src/main/java/com/ivy/data/testing/FakeAccountRepository.kt
ivy-data-testing/src/main/java/com/ivy/data/testing/FakeCategoryRepository.kt
ivy-data-testing/src/test/java/com/ivy/data/testing/FakeAccountRepositoryTest.kt
ivy-data-testing/src/test/java/com/ivy/data/testing/FakeCategoryRepositoryTest.kt
ivy-data/src/main/java/com/ivy/data/repository/CategoryRepository.kt
ivy-data/src/main/java/com/ivy/data/repository/impl/CategoryRepositoryImpl.kt
ivy-data/src/main/java/com/ivy/data/repository/mapper/CategoryMapper.kt
ivy-data/src/test/java/com/ivy/data/model/primitive/AssetCodeTest.kt
ivy-data/src/test/java/com/ivy/data/model/primitive/IconIdTest.kt
ivy-data/src/test/java/com/ivy/data/model/primitive/NotBlankTrimmedStringTest.kt
ivy-data/src/test/java/com/ivy/data/model/primitive/PositiveDoubleTest.kt
ivy-data/src/test/java/com/ivy/data/repository/impl/AccountRepositoryImplTest.kt
ivy-data/src/test/java/com/ivy/data/repository/impl/CategoryRepositoryImplTest.kt
ivy-data/src/test/java/com/ivy/data/repository/mapper/AccountMapperTest.kt
ivy-data/src/test/java/com/ivy/data/repository/mapper/CategoryMapperTest.kt

- Data Layer: Categories Repository is now implemented and tested
- Data Layer: Fake Account Repository is now implemented and tested; more tests are added for Account Repository Implementation class
- Closes #2746 
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed check and explore the logs to see why it has failed.
[Detekt](https://detekt.dev/) is a static code analyzer for Kotlin that we use to enforce code readibility and good practices.
**To run Detekt locally:**
```
./gradlew detekt
```
If the Detekt errors are caused by a legacy code, you can suppress them using a basline.
**Detekt baseline** …

Fix issue 2746 - Data Layer: Categories Repository

---

.github/workflows/issue_assign.yml
automations/base/src/main/kotlin/ivy/automate/base/github/GitHubService.kt
automations/base/src/main/kotlin/ivy/automate/base/github/GitHubServiceImpl.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/ActionExecutor.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/CommentAnalyzer.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/Constants.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/DetermineAction.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/Main.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/ActionExecutorTest.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/CommentAnalyzerTest.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/DetermineActionTest.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Fix automation

---

automations/issue-assign/src/main/kotlin/ivy/automate/issue/CommentAnalyzer.kt
automations/issue-assign/src/main/kotlin/ivy/automate/issue/DetermineAction.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/CommentAnalyzerTest.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/DetermineActionTest.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Automation fixes

---

.idea/kotlinScripting.xml
automations/issue-assign/src/main/kotlin/ivy/automate/issue/CommentAnalyzer.kt
automations/issue-assign/src/test/kotlin/ivy/automate/issue/CommentAnalyzerTest.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Restrict the CommentAnalyzer.kt only to the "I'm on it" magic words

---

screen-accounts/src/main/java/com/ivy/accounts/AccountsTab.kt

- a The account cards are smaller in size.
- b
- c
- d
- a nothing
- b
- c
- a it won't happen
- b
- c
- Closes #2587
If you see any of the PR checks failing (❌) go to …

MayankRaje-fix-issue-2587: Make the account cards smaller

---

screen-exchange-rates/src/main/java/com/ivy/exchangerates/ExchangeRatesScreen.kt
screen-exchange-rates/src/main/java/com/ivy/exchangerates/ExchangeRatesViewModel.kt

- ComposeViewModel
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed …

refs #2623: Migrate screen-exchange-rates to ComposeViewModel

---

screen-reports/src/main/java/com/ivy/reports/ReportScreen.kt
screen-reports/src/main/java/com/ivy/reports/ReportViewModel.kt

[Screen_recording_20231015_221215.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/20263744/02468c19-a763-42fc-a3f3-3698dfe64a55)
- Some Reports functionality
- Closes #2628 
If you see any of the PR checks failing …

refs #2628: Migrate screen-reports to ComposeViewModel

---

.github/workflows/test.yml
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

- [No] 🎬 I've attached a **screen recoding** of the changes. 
- a Added [Kover](https://github.com/Kotlin/kotlinx-kover) for generating code coverage report
- b Added a new job in the existing workflow to upload  the generated code coverage reports in GitHub artifact 
- c The code coverage report will be run in CI only if the unit test workflow completed
- d using `./gradlew koverHtmlReport` will generate the report locally 
- a None
- b
- c
- a None
- b
- c
Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/2722)**.
- Closes …

Add Kover Code Coverage

---

screen-reports/src/main/java/com/ivy/reports/ReportScreen.kt
screen-reports/src/main/java/com/ivy/reports/ReportScreenEvent.kt
screen-reports/src/main/java/com/ivy/reports/ReportViewModel.kt

[Screen_recording_20231019_204209.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/20263744/ef8e133f-cd03-4890-923c-a16c970160db)
- Fixed skip, skip all and pay buttons
- Closes #1086
If you see any of the PR checks …

refs #1086: Fix skip, skip all and pay buttons on Reports screen

---

screen-accounts/src/main/java/com/ivy/accounts/AccountsTab.kt

The account UI has been updated 
- a Nothing
- b
- c
- a Nothing
- b
- c
- Closes #2799 
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or …

[FEATURE-2799] Fixing Account Tab UI

---

temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/ChoosePeriodModal.kt

[Screen_recording_20231023_215141.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/20263744/bae8890d-add7-4c45-817f-7e7557e66c4f)
- Include the last day for time period
- a
- b
- c
- a
- b
- c
- Closes #2798 
If you …

refs #2798: Fix TimePeriod last day not shown

---

screen-accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/68247763/2517b34a-9e87-4656-82b7-566a95729d75
- Based on @ILIYANGERMANOV 's comment in Issue #2811 , I made sure that the balance in the account overview also takes the excluded accounts into account
- Nothing (AFAIK).
- I eat a hat, if there's a case in which it does not work.
- Closes #2811 
> Replace `ISSUE_NUMBER` with your issue number (for …

Money total sum customization

---

temp-legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionSectionDivider.kt

Before | After
---|---
- Closes #2858

correct the direction of expand arrow of upcoming and overdue sections

---

app/src/main/java/com/ivy/wallet/PaymentTileService.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/45493154/b88cefb5-6a05-49eb-b6f0-90a37da5fbb7 
https://github.com/Ivy-Apps/ivy-wallet/assets/45493154/116e746e-820e-4369-b103-8447a6c0d783
- Closes #2864

Fix issue 2864

---

.github/workflows/test.yml
app/build.gradle.kts
ivy-data/src/test/java/com/ivy/data/repository/mapper/AccountMapperTest.kt
ivy-data/src/test/java/com/ivy/data/repository/mapper/CategoryMapperTest.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Fixes and misc

---

temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/BalanceRow.kt
temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/wallet/AmountCurrency.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/122120289/a9420494-8241-471f-ab1d-9eb787f92afa
- a
- b
- c
- d
- a
- b
- c
- a
- b
- c
If you see any of the PR checks failing (❌) go to …

issue2880: replace four stars as hiding balance charcatars to one star

---

screen-categories/src/main/java/com/ivy/categories/CategoriesScreen.kt

Fixed the cards spacing.
- Closes #2885

Categories screen cards spacing fix

---

ivy-data/src/main/java/com/ivy/data/db/migration/Migration124to125_LoanEditDateTime.kt

Fixes the App crash when updating from a very old apk
- a
- b
- c
- d
- a
- b
- c
- a
- b
- c
- Closes #2891 
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) …

[IVY-2891] Fix Loan Migration Failure

---

buildSrc/src/main/kotlin/ivy.detekt.gradle.kts
config/detekt/baseline.yml
config/detekt/config.yml
gradle/libs.versions.toml

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Detekt `IvyExplicit` rules

---

config/detekt/baseline.yml
config/detekt/config.yml
gradle/libs.versions.toml

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Bump Ivy detekt

---

config/detekt/baseline.yml
config/detekt/config.yml
gradle/libs.versions.toml

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Update Ivy Detekt to 0.0.5

---

.github/workflows/stale.yml

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Don't close issues & PRs having "keep" label

---

.github/workflows/stale.yml

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …

Keep P0s from getting closed

---

temp/old-design/src/main/java/com/ivy/design/utils/Compose.kt

- a
- b
- c
- d
- a
- b
- c
- a
- b
- c
- Closes #2903 
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to …

Fix missing buttons caused by broken `thenIf {}`

---

screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
shared/resources/src/main/res/values-ar/strings.xml
shared/resources/src/main/res/values-bg/strings.xml
shared/resources/src/main/res/values-es/strings.xml
shared/resources/src/main/res/values-hi/strings.xml
shared/resources/src/main/res/values-id/strings.xml
shared/resources/src/main/res/values-in/strings.xml
shared/resources/src/main/res/values-it/strings.xml
shared/resources/src/main/res/values-kn/strings.xml
shared/resources/src/main/res/values-mn/strings.xml
shared/resources/src/main/res/values-pl/strings.xml
shared/resources/src/main/res/values-ru/strings.xml
shared/resources/src/main/res/values/strings.xml

Fixed issue 2927
- Closes #2927 
> Replace `2927` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

Issue 2927

---

screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt

The excluded Amount issue in the Account tab is fixed
- Closes #2927 

Fix Issue #2927

---

screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt

Fix issue 2927

---

gradle/libs.versions.toml

Issue 2942 issue fixed
Will close #2942 issue

ISSUE #2942

---

shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeAccountDao.kt
shared/data/src/test/java/com/ivy/data/dao/FakeAccountDaoTest.kt

- updated few function in fake account dao
- implemented tests for fake account dao 
- N/A
- N/A
- Closes #2931  …

Fix issue 2931

---

shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeCategoryDao.kt
shared/data/src/test/java/com/ivy/data/dao/FakeCategoryDaoTest.kt

- updated fake category dao 
- implemented fake category dao test
- N/A
- N/A
- Closes #2932  …

Fix issue 2932

---

shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeTransactionDao.kt
shared/data/src/test/java/com/ivy/data/dao/FakeTransactionDaoTest.kt

- updated transaction dao 
- implemented transaction dao tests
- N/A
- N/A
- Closes #2933  …

Fix issue 2933

---

screen/accounts/build.gradle.kts
screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
screen/categories/build.gradle.kts
screen/categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
temp/legacy-code/src/main/java/com/ivy/legacy/IvyWalletCtx.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/69354473/9bb1688d-6c1c-4a57-bb1c-33fed73540e4
No Risk Factors
- Closes #2938 
GitHub Actions failing? Read our [CI Troubleshooting …

fixed issue #2938

---

gradle/libs.versions.toml
screen/accounts/src/main/java/com/ivy/accounts/AccountsEvent.kt
screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsViewModel.kt
temp/legacy-code/src/main/java/com/ivy/legacy/data/model/AccountData.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/account/CalcAccBalanceAct.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/account/CalcAccIncomeExpenseAct.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/viewmodel/account/AccountDataAct.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/wallet/CalcWalletBalanceAct.kt

- migrate account tab to use new account repository
- replaced usages of legacy `Account` model with new `Account` model
- there's the possibility that calculations for account balance could break
- listing accounts could break
- non discovered
- Closes #2961 
> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the …

Fix issue 2961

---

screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt

The video demonstration of the added feature:
https://github.com/Ivy-Apps/ivy-wallet/assets/50723693/1092645a-52fb-4788-b68c-71403e29005e
The Account Transfer Screen before (there is no category):
- Now Account Transfer transaction has the ability to add the type of category 
*I also attach the screenshot confirmation where we see:*
- the category ID created when creating the Account Transfer in Logs
- the same category ID appearing in the HomeScreen in Transactions section
- So far, tested everything. …

Fix issue #2971

---

temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/wallet/AmountCurrency.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt

*Before (no category for account transfer transaction card):*
*After (category is present in a column):*
- Added a category to Account Transfer Transaction Card
- For now, nothing. Everything is tested
- For now, nothing.
- Closes #2984
> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when …

[FEATURE] Fix issue #2984: Added UI to reflect category of Account Transfers

---

temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/EditBottomSheet.kt

Before:
There was no padding between the accounts while adding a transaction.
After:
There is a padding of 8dp between accounts while adding transaction.
- a
- b
- c
Nothing
Nothing
- Closes #2986 
> …

Added padding between accounts when creating transaction

---

ci-actions/compose-stability/ivy-compose-stability-baseline.txt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionEvent.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionState.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
shared/data/src/main/java/com/ivy/data/db/dao/read/TagDao.kt
shared/data/src/main/java/com/ivy/data/di/RepositoryBindingsModule.kt
shared/data/src/main/java/com/ivy/data/di/RoomDbModule.kt
shared/data/src/main/java/com/ivy/data/model/primitive/TagId.kt
shared/data/src/main/java/com/ivy/data/repository/TagsRepository.kt
shared/data/src/main/java/com/ivy/data/repository/impl/TagsRepositoryImpl.kt
shared/data/src/main/java/com/ivy/data/repository/mapper/TagMapper.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/wallet/CalcWalletBalanceAct.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/AddOrEditTagModal.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/AddTagButton.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/ShowTagModal.kt

- a
- b
- c
- a
- b
- a
- b
GitHub …

Tags and Transaction Association

---

README.md

- a
- b
- c
- a
- b
- a
- b
GitHub …

Join our Telegram Channel Spelling is corrected

---

temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/exchange/SyncExchangeRatesAct.kt

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fix currency-api link

---

temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt
temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/CalculatorModal.kt

- a
- b
- c
- a
- b
- a
- b
- Closes #3003 
GitHub Actions …

Fixed alignment issue with buttons of calculator screen

---

ci-actions/compose-stability/ivy-compose-stability-baseline.txt
screen/reports/src/main/java/com/ivy/reports/FilterOverlay.kt
screen/reports/src/main/java/com/ivy/reports/ReportFilter.kt
screen/reports/src/main/java/com/ivy/reports/ReportScreen.kt
screen/reports/src/main/java/com/ivy/reports/ReportScreenEvent.kt
screen/reports/src/main/java/com/ivy/reports/ReportScreenState.kt
screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsViewModel.kt
shared/base/src/main/java/com/ivy/base/legacy/LegacyTag.kt
shared/base/src/main/java/com/ivy/base/legacy/Transaction.kt
shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeTransactionDao.kt
shared/data/src/main/java/com/ivy/data/db/dao/read/TagAssociationDao.kt
shared/data/src/main/java/com/ivy/data/db/dao/read/TagDao.kt
shared/data/src/main/java/com/ivy/data/db/dao/read/TransactionDao.kt
shared/data/src/main/java/com/ivy/data/di/RoomDbModule.kt
shared/data/src/main/java/com/ivy/data/model/Transaction.kt
shared/data/src/main/java/com/ivy/data/repository/TagsRepository.kt
shared/data/src/main/java/com/ivy/data/repository/TransactionRepository.kt
shared/data/src/main/java/com/ivy/data/repository/impl/TagsRepositoryImpl.kt
shared/data/src/main/java/com/ivy/data/repository/impl/TransactionRepositoryImpl.kt
shared/data/src/main/java/com/ivy/data/repository/mapper/TagMapper.kt
shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt
shared/data/src/test/java/com/ivy/data/repository/impl/TransactionRepositoryImplTest.kt
shared/data/src/test/java/com/ivy/data/repository/mapper/TransactionMapperTest.kt
shared/resources/src/main/res/values/strings.xml
temp/legacy-code/src/main/java/com/ivy/legacy/datamodel/temp/TransactionExt.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/transaction/TrnsWithDateDivsAct.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/pure/transaction/TrnDateDividers.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/ShowTagModal.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt

- a This PR adds the fix to display the tags on the homescreen tab
- b This PR adds the ability to filter transactions based on tags in ReportsScreen
- <img src="https://github.com/Ivy-Apps/ivy-wallet/assets/42895647/a7b19f39-1d3b-413a-8c90-5220b794f844" width=50% height=50%>
- N/A
- a Tags Won't be seen on the main Screen
> Replace `ISSUE_NUMBER` with the number of the …

[IVY-2863] Tags UI Composables

---

screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
screen/settings/src/main/java/com/ivy/settings/SettingsViewModel.kt
temp/legacy-code/src/main/java/com/ivy/legacy/utils/DateExt.kt

- [&check;] The PR is submitted to the `main` branch.
- [&check; ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [&check;] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [&check; ] I confirm that I've run the code locally and everything works as expected.
- [&cross;] 🎬 I've attached a **screen recoding** of the changes. 
Changed date time format  for exports and backup functionality from "dd MMM HH:mm" to "yyyyMMdd_HH:mm" ISO Format
Check **[Ivy Wallet …

Changed date time format to iso 8601 for exports and backup

---

screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionState.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
screen/reports/src/main/java/com/ivy/reports/FilterOverlay.kt
screen/reports/src/main/java/com/ivy/reports/ReportFilter.kt
screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
shared/data/src/androidTest/java/com/ivy/data/backup/BackupDataUseCaseAndroidTest.kt
shared/data/src/main/java/com/ivy/data/backup/BackupDataUseCase.kt
shared/data/src/main/java/com/ivy/data/backup/IvyWalletCompleteData.kt
shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeTagAssociationDao.kt
shared/data/src/main/java/com/ivy/data/db/dao/fake/FakeTagDao.kt
shared/data/src/main/java/com/ivy/data/repository/TagsRepository.kt
shared/data/src/main/java/com/ivy/data/repository/fake/FakeTagRepository.kt
shared/data/src/main/java/com/ivy/data/repository/impl/TagsRepositoryImpl.kt
shared/data/src/test/java/com/ivy/data/backup/BackupDataUseCaseTest.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/AddTagButton.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/ShowTagModal.kt

- a Added Fix Which causes tag not to be selected in EditTransactionScreen
- b UX Fix for FilterOverly in ReportsScreen
- c BackUp and Restore for Tags
- a
- b
- a
- b
- Closes #2863 
> **!Note:** Do **not** …

Tags Backup & Restore

---

shared/resources/src/main/res/values-ar/strings.xml
shared/resources/src/main/res/values-bg/strings.xml
shared/resources/src/main/res/values-es/strings.xml
shared/resources/src/main/res/values-hi/strings.xml
shared/resources/src/main/res/values-id/strings.xml
shared/resources/src/main/res/values-in/strings.xml
shared/resources/src/main/res/values-it/strings.xml
shared/resources/src/main/res/values-kn/strings.xml
shared/resources/src/main/res/values-mn/strings.xml
shared/resources/src/main/res/values-pl/strings.xml
shared/resources/src/main/res/values-ru/strings.xml
shared/resources/src/main/res/values/strings.xml
temp/legacy-code/src/main/java/com/ivy/legacy/ui/SearchInput.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/ShowTagModal.kt

- [Y] The PR is submitted to the `main` branch.
- [Y ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ Y] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [ Y] I confirm that I've run the code locally and everything works as expected.
- [ Y] 🎬 I've attached a **screen recoding** of the changes. 
1.Global search
2.Exchange rate screen
3.Search tags screen
- Closes #3011 
> Replace `3011` with the number of the GitHub issue that this …

Fix issue #3011

---

shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/loantrasactions/LTLoanMapper.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/loantrasactions/LTLoanRecordMapper.kt
temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/loantrasactions/LoanTransactionsCore.kt
temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt

- a Fixed the Issue where wrong transaction type was selected when loan increase was selected
- b Fixed Issue where Transaction was not displayed if empty note was selected in Loans
- c
- a
- b
- a
- b
- Closes #2981 
> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR …

Fixed Loan Increase Main Transaction Issue

---

screen/loans/build.gradle.kts
screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
screen/planned-payments/build.gradle.kts
screen/planned-payments/src/main/java/com/ivy/planned/list/PlannedPaymentsLazyColumn.kt
screen/planned-payments/src/main/java/com/ivy/planned/list/PlannedPaymentsScreen.kt
screen/reports/build.gradle.kts
screen/reports/src/main/java/com/ivy/reports/ReportScreen.kt
temp/legacy-code/src/main/java/com/ivy/legacy/IvyWalletCtx.kt

https://github.com/Ivy-Apps/ivy-wallet/assets/69354473/106b542d-e633-4e7e-b8d7-1c106945c1a4
Scroll position is getting remembered in Loans, PlannedPayments and Reports Screen
No risk factors
- Closes #3021  …

fix issue 3021

---

shared/data/src/main/java/com/ivy/data/repository/impl/CategoryRepositoryImpl.kt

- Added a Singleton annotation to make the CategoryRepoImpl a single instance from which we can get our cached categories
- Checked & tested
- Checked & tested
- Closes #2990 
> **!Note:** Do **not** link the …

Addition of the Singleton to CategoryRepositoryImpl as part of the memoization 

---

shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt
shared/data/src/test/java/com/ivy/data/repository/impl/TransactionRepositoryImplTest.kt
shared/data/src/test/java/com/ivy/data/repository/mapper/TransactionMapperTest.kt

This patch fixes the account balance calculation in som edge cases after a backup is imported. Fixes errors in the following scenarios:
```json
"transactions": [
{
"accountId": "f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
"type": "EXPENSE",
"title": ""
"amount": 20.0,
"toAmount": 20.0,
"dateTime": 1710801642282,
"categoryId": "7d0435cf-ee90-4717-b408-9ceba878f6ef",
"id": "4bcd6bfd-6c42-438e-b75c-5b4c5d97df10"
},
{
"accountId": "f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
"type": "EXPENSE",
"amount": 60.0,
"toAmount": 60.0,
"description": "",
"dateTime": 1710801631309,
"categoryId": "ae92e17a-5cbd-47ab-bd2a-6f9d4f13744b",
"id": "22744a09-1dbb-460c-a740-ca2cb194f32f"
},
]
``` …

Fix balance calculation if description and/or title are blank strings

---

shared/data/src/main/java/com/ivy/data/remote/responses/ExchangeRatesResponse.kt

- a Fixes Exchange Rates Not Saving to Database
- b
- c
- a
- b
- a
- b
- Closes #3035 #3002  …

[IVY-3035] Fix Exchange Rates not Saving to Database

---

temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/AccountCreator.kt

- a Accounts with Initial Balance can now be created.
- b
- c
- a
- b
- a
- b
- Closes #3037  …

[IVY-3037] Fix Accounts With Inital Balance

---

screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt

- a LoanAmout was used instead of LoanTotalAmount 
- b
- c
- a
- b
- a
- b
- Closes #2973  …

[IVY-2973] Fix Incorrect Left to Pay Amount In Loans

---

screen/transactions/src/main/java/com/ivy/transactions/TransactionsViewModel.kt

- invoked `categoryRepository.onDelete()` which was unused earlier
- Closes #3048

fix issue: delete category not working

---

.idea/.gitignore
screen/transactions/src/main/java/com/ivy/transactions/TransactionsScreen.kt

- The modal now shows `NotBlankTrimmedString.value`.
- Closes #3046

fix issue: wrong label shown on category deletion modal

---

temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt

Before
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/e070b2cb-673b-4e9e-a0a6-758b0ea7a614
Center the text inside the numeric keypad, set the default value for amount to 0 instead of the empty string as before so we can use +/- when opening the accountModal when user has not entered any numbers yet (video attached)
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/7173bc59-b136-4dfd-af23-50e523d0bcf8
No risk factors
- Closes #3054

Fix issue 3054

---

.github/PULL_REQUEST_TEMPLATE.md
docs/guidelines/Data-Modeling.md
docs/guidelines/Error-Handling.md
docs/guidelines/Screen-Architecture.md

- a
- b
- c
- a
- b
- a
- b
GitHub …

Guidelines

---

temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/PreloadDataLogic.kt

Result:
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/523922dc-aee0-4cef-a44f-af4121e6bbb9
- Using categoryRepository instead of WriteCategoryDao for function preloadCategory
No risk factors
- Closes #3056

Fix error when the user clicks "Skip-Skip" default categories aren't added

---

.github/ISSUE_TEMPLATE/bug_report.yml
gradle/libs.versions.toml
shared/domain/build.gradle.kts

- a
- b
- c
- a
- b
- a
- b
GitHub …

Bump app version to "4.6.0" (160)

---

temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/loantrasactions/LoanTransactionsCore.kt

- a 
- b
- c
- a
- b
- a
- b
- Closes #3047 
GitHub Actions …

[IVY-3047] Fix Multiple Loan Categories

---

screen/main/src/main/java/com/ivy/main/MainBottomBar.kt
temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/IvyOutlinedButton.kt
temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt

+ Adjust padding for responsive UI
| Before    | After |
| -------- | ------- |
|![Screenshot_20240410_085350](https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/12d43f2b-df79-46ce-9eac-08dbfd51872f)  | ![Screenshot_20240410_085553](https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/214c79cd-cd23-4ee0-b29c-b15832f80528) |
|![small_account](https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/9b2375a1-8863-45bf-a484-e5e047c9b79a) | ![fixed_small](https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/8f5e578d-66cb-4ece-944a-570e81b3f456)  |
|![a](https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/6135428b-d481-47b4-a367-8fb5e823a551) …

Fix UI amount keyboard, outline button

---

gradle/libs.versions.toml
screen/home/src/main/java/com/ivy/home/customerjourney/CustomerJourneyCardsProvider.kt
shared/data/core/src/test/java/com/ivy/data/ArbAccountEntity.kt
shared/data/core/src/test/java/com/ivy/data/repository/mapper/AccountMapperPropertyTest.kt
shared/data/core/src/test/java/com/ivy/data/repository/mapper/AccountMapperTest.kt
shared/data/model-testing/src/main/java/com/ivy/data/model/testing/ArbCategory.kt
shared/data/model-testing/src/test/java/com/ivy/data/model/testing/ArbCategoryTest.kt
shared/data/model-testing/src/test/java/com/ivy/data/model/testing/ArbTransactionTest.kt
shared/domain/build.gradle.kts
shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt
shared/domain/src/main/java/com/ivy/domain/usecase/csv/ReadCsvUseCase.kt
shared/domain/src/test/java/com/ivy/domain/usecase/csv/ExportCsvUseCasePropertyTest.kt

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fixes before release

---

widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fix an issue with having multiple balance widgets on screen

---

screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionState.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
screen/reports/src/main/java/com/ivy/reports/FilterOverlay.kt
screen/reports/src/main/java/com/ivy/reports/ReportFilter.kt
screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/AddTagButton.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/tags/ShowTagModal.kt

- a Fixed Tag De Select Not working
- b
- c
- a
- b
- a
- b
- Closes #3126  …

[IVY-3126] Fix TagSelection

---

screen/home/src/main/java/com/ivy/home/HomeMoreMenu.kt
screen/piechart/src/main/java/com/ivy/piechart/action/PieChartAct.kt

+ Add style for "Quick access" text
+ add null element in order to show unspecified category
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/de099d12-ad71-4670-88fe-f79b1f59fc42
No
- Closes #3137

Fix error not show Unspecified Category in PieChart screen

---

screen/piechart/src/main/java/com/ivy/piechart/action/PieChartAct.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsScreen.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsViewModel.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/ItemStatisticToolbar.kt

+ Fix error crash 
+ Hide edit and delete for Account Transfer Catergory (I hide it because I see it can cause many other errors, because the Account Transfer Category is not stored in the Category table of the DB.)
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/4d60995e-b088-44ba-8e39-79f624b48e29
- Closes #3156

Fix error crash and improvement UX for account transfer type in Transaction screen

---

CONTRIBUTING.md

- a
- b
- c
- a
- b
- a
- b
- Closes #3169
GitHub Actions …

Add note to install git lfs in contributing guide 

---

shared/data/core/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt

- [ ✅] The PR is submitted to the `main` branch.
- [ ✅] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ ✅] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ ✅] I confirm that I've run the code locally and everything works as expected.
- [ ✅] 🎬 I've attached a **screen recoding** of the changes. 
Date Gaps due to timezone issue fixed
> Tip: you can attach screenshots using a markdown table.
Before :
https://github.com/Ivy-Apps/ivy-wallet/assets/72225636/c52effea-0dc9-451a-9173-57915284b8be
After : …

[FIX] TimeZone Issue Fix

---

docs/CI-Troubleshooting.md
docs/Guidelines.md

fix some comments
- a
- b
- c
- a
- b
- a
- b …

docs: fix some comments

---

gradle/libs.versions.toml
shared/ui/core/src/main/res/values/strings.xml
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fixes before the release

---

.github/workflows/internal_release.yml
app/src/main/AndroidManifest.xml
fastlane/Fastfile
gradle/libs.versions.toml
shared/data/core/schemas/com.ivy.data.db.IvyRoomDatabase/128.json

- a
- b
- c
- a
- b
- a
- b
GitHub …

Improve release workflow

---

app/src/main/java/com/ivy/wallet/RootActivity.kt
gradle/libs.versions.toml
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
shared/ui/core/src/main/res/values/strings.xml

- a
- b
- c
- a
- b
- a
- b
- Closes #3249 
> Replace `3249` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.
GitHub Actions failing? Read …

Fix issue 3249

---

.github/workflows/internal_release.yml

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fix automations

---

.github/workflows/automatic_release.yml
.github/workflows/internal_release.yml

- a
- b
- c
- a
- b
- a
- b
GitHub …

Automate releases

---

.github/workflows/internal_release.yml

- a
- b
- c
- a
- b
- a
- b
GitHub …

Fix the internal_release.yml

---

.github/workflows/automatic_release.yml
.github/workflows/internal_release.yml

- a
- b
- c
- a
- b
- a
- b
GitHub …

Improve auto-release workflow

---

.github/workflows/internal_release.yml
app/src/main/AndroidManifest.xml

N/A
- Removes unnecessary permission blocking the Google PlayStore release.
- ...
- ...
- ...
- ...

Remove unnecessary permission

---

temp/legacy-code/src/main/java/com/ivy/legacy/domain/data/IvyCurrency.kt

Added the new tonchain currency into the currency list

Added the tonchain currency

---

gradle/libs.versions.toml
temp/legacy-code/src/main/java/com/ivy/legacy/domain/data/IvyCurrency.kt

Commented out the (com.google.android.play:asset-delivery)  library that was causing the issue and found we have not use the code of the given library into our project. 
Closes #3328

Remove the library that causing 3328

---

.github/PULL_REQUEST_TEMPLATE.md

- Deleted `main` branch checkbox
- In code view: deleted unnecessary empty lines, clarified comments
Before|After
-------|-------
- People still might be confused
- It's a doc
- Closes #3335

PR template - dev exp enhancements

---

app/build.gradle.kts

- The new name reflects the full-featured nature of the application 
- Closes #3361

Remove "Demo" from application name

---

.github/workflows/internal_release.yml

- Replaced '\n\n' with two spaces in the `CAPTION` variable to ensure proper display in release messages.
- Closes #3374

fix: Replace newlines in release caption with spaces

---

temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/HistoryDateDivider.kt

Reverts Ivy-Apps/ivy-wallet#3351
- Closes N/A

Revert "Change dateNowUTC() to dateNowLocal() because dateNowUTC() giving wrong date"

---

app/src/main/java/com/ivy/wallet/RootActivity.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
temp/legacy-code/src/main/java/com/ivy/legacy/IvyWalletCtx.kt
temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt

https://github.com/user-attachments/assets/6b11fc0f-86e9-4b44-bd93-38340bfee5ca
- Ensure the time picker displays the correct time when reopened
- Automatically switch between 12-hour and 24-hour modes based on system settings
Before|After
---|--
https://github.com/user-attachments/assets/efe99c73-1d56-4f41-84a0-1b3f68ee52c0 | https://github.com/userattachments/assets/efac3ddc-4923-41b5-9533-6a290b074c52
- Closes #3394 

fix: Correct time picker display and mode switching

---

shared/data/core/src/androidTest/java/com/ivy/data/backup/BackupDataUseCaseAndroidTest.kt
shared/data/core/src/main/java/com/ivy/data/backup/BackupDataUseCase.kt
shared/data/core/src/main/java/com/ivy/data/backup/IvyWalletCompleteData.kt
shared/data/core/src/test/java/com/ivy/data/backup/BackupDataUseCaseTest.kt

- I've fixed Tag data not backing up
Before|After
---|---
1. none
- ...
- ...
- ...
- ...
- Closes #3445 

[IVY-3445] Fix Tag Backup and Restore

---

app/src/main/java/com/ivy/wallet/RootActivity.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewEvent.kt
screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
shared/base/src/main/java/com/ivy/base/time/TimeProvider.kt
shared/base/src/main/java/com/ivy/base/time/impl/DeviceTimeProvider.kt
shared/ui/core/src/main/java/com/ivy/ui/di/IvyUiBindings.kt
shared/ui/core/src/main/java/com/ivy/ui/time/DevicePreferences.kt
shared/ui/core/src/main/java/com/ivy/ui/time/impl/AndroidDateTimePicker.kt
shared/ui/core/src/main/java/com/ivy/ui/time/impl/AndroidDevicePreferences.kt
shared/ui/core/src/main/java/com/ivy/ui/time/impl/DateTimePicker.kt
shared/ui/core/src/main/java/com/ivy/ui/time/impl/IvyTimeFormatter.kt
shared/ui/core/src/test/java/com/ivy/ui/time/impl/IvyTimeFormatterTest.kt
temp/old-design/src/main/java/com/ivy/design/utils/Preview.kt

- I've fixed...
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes N/A

Fix updating transactions's time

---

temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/ChooseIconModal.kt

https://github.com/user-attachments/assets/b4f16edc-e4e2-4b53-957b-733c4097966e
adjust category text color to adapt to dark mode theme
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3469

fix: adjust category text color to adapt to dark mode theme

---

screen/contributors/src/main/java/com/ivy/contributors/ContributorsScreen.kt

Added a condition to open the profile in contributors screen
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3479 

Fix App crash issue in Contributor screen

---

screen/planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedViewModel.kt

- I've fixed EditPlannedViewModel such that all it's mutableStates uses by delegate
-N/A
- -N/A
- Closes #3529 

[Refactor] EditPlannedViewModel: using by delegation for mutable states

---

screen/loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt

https://github.com/user-attachments/assets/c8af829e-0636-4919-98e0-239e71c22e4d
- I've fixed the bug of Loan transactions disappears
- N/A
- N/A
- Closes #3546 

Fix of Loan transactions disappears

---

screen/settings/src/main/java/com/ivy/settings/SettingsScreen.kt

https://github.com/user-attachments/assets/73c50cdc-f114-46f1-bedc-c05b5119c7fc
- fixed some icon padding to make the list consistent
- no idea how it looks like on smaller screens, can't test it
- Closes #3549 

Improve icons size consistence in Settings

---

widget/add-transaction/src/main/res/drawable/widget_compact_divider.xml
widget/add-transaction/src/main/res/layout/widget_add_transaction_compact.xml

A divider in a compact widget was added.
Before : 
After : 
N/A
N/A
- Closes N/A

Add widget compact divider

---

shared/ui/core/src/main/java/com/ivy/ui/time/impl/AndroidDateTimePicker.kt

N/A
- I've the horizontal alignment of timepicker circle to be centered horizontally
Before|After
---|---
- Harmless change
- N/A
- Closes #3599

Align time picker circle to centered horizontally

---

screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt

[](https://github.com/user-attachments/assets/a9cd6019-a883-4b05-bb1f-d2ac90fc01d9)
- I've fixed Loan Screen Bottom Spacing Issue
-N/A
-N/A
- Closes #3593 

[BUG]Loan Screen Bottom Spacing Issue Fixed

---

screen/home/src/main/java/com/ivy/home/HomeState.kt
screen/home/src/main/java/com/ivy/home/HomeTab.kt
screen/home/src/main/java/com/ivy/home/HomeViewModel.kt
screen/reports/src/main/java/com/ivy/reports/ReportScreen.kt
screen/reports/src/main/java/com/ivy/reports/ReportScreenState.kt
screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
screen/search/src/main/java/com/ivy/search/SearchScreen.kt
screen/search/src/main/java/com/ivy/search/SearchState.kt
screen/search/src/main/java/com/ivy/search/SearchViewModel.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsScreen.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsState.kt
screen/transactions/src/main/java/com/ivy/transactions/TransactionsViewModel.kt
shared/domain/src/main/java/com/ivy/domain/features/Features.kt
shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt
temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/Transactions.kt

https://github.com/user-attachments/assets/820cfa47-0353-45bc-85e3-50ea37b6e199
- Added optional functionality to show account colors in transaction
-  N/A
-  N/A
- Closes #3545 

[Feature] Added color to accounts labels in transactions list Behind IvyFeatureToggle
