- app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
- Closes #18 
- Added swipe gesture on the HomeTab Screen to allow menu more to be opened as a better UX for users
> Closes #18; implemented swipe gesture to open more menu screen

- app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt
- Closes #17 
- Simplified UX Scrolling 
- Video Preview -> https://user-images.githubusercontent.com/42895647/142450420-9f253166-5204-44fb-84bb-942021caa5f3.mp4
> Shifted to a  Simple Animation in ItemStatisticScreen

- app/src/main/java/com/ivy/wallet/Constants.kt
- app/src/main/java/com/ivy/wallet/ui/home/HomeHeader.kt
- app/src/main/java/com/ivy/wallet/ui/home/HomeTab.kt
successfully.
- Closes #62 
- Smoother Scroll and animation
Video Preview ->  https://user-images.githubusercontent.com/42895647/143041982-be14ea76-720f-45da-b75c-216762902459.mp4
> Smoother HomeUI Scroll and Animation

- app/src/main/java/com/ivy/wallet/logic/csv/CSVImporter.kt
- app/src/main/java/com/ivy/wallet/logic/csv/CSVMapper.kt
@ILIYANGERMANOV thanks for the review of #201 and the refactoring! Seems mostly very reasonable to me :)
I fixed two more issues:
- When merging two rows, we need to decrement the `rowsFound` field in the `ImportResult`. Otherwise for each merged transaction, one will show as failed in the results.
- I just noticed, that Financisto messed up its CSV exports and puts the location in the same field as where it specifies whether it was a transfer or not. Thus this field may contain arbitrary data which caused the previous implementation to fail. Note that this may produce unexpected results if the location name contains "transfer", "expense" or "income", but there seems no easy way to avoid this and it seems very unlikely that a location contains these strings.
I hope this does not affect …
> Fix Financisto CSV-Import

- app/src/main/java/com/ivy/wallet/ui/csvimport/flow/ImportFrom.kt
- app/src/main/java/com/ivy/wallet/ui/edit/core/EditBottomSheet.kt
- app/src/main/java/com/ivy/wallet/ui/home/CustomerJourney.kt
- app/src/main/java/com/ivy/wallet/ui/home/HomeMoreMenu.kt
- app/src/main/java/com/ivy/wallet/ui/onboarding/components/Suggestions.kt
- app/src/main/java/com/ivy/wallet/ui/onboarding/steps/OnboardingAccounts.kt
- app/src/main/java/com/ivy/wallet/ui/onboarding/steps/OnboardingCategories.kt
- app/src/main/java/com/ivy/wallet/ui/onboarding/steps/OnboardingSplashLogin.kt
- app/src/main/java/com/ivy/wallet/ui/paywall/PlansSheet.kt
- app/src/main/java/com/ivy/wallet/ui/planned/list/PlannedPaymentCard.kt
- app/src/main/java/com/ivy/wallet/ui/reports/FilterOverlay.kt
- app/src/main/java/com/ivy/wallet/ui/reports/ReportScreen.kt
- app/src/main/java/com/ivy/wallet/ui/search/SearchScreen.kt
- app/src/main/java/com/ivy/wallet/ui/settings/SettingsScreen.kt
- app/src/main/java/com/ivy/wallet/ui/theme/IvyTypography.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/BalanceRow.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/IvyBorderButton.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/IvyButton.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/IvyCheckbox.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/IvyOutlinedButton.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/OnboardingComponents.kt
- app/src/main/java/com/ivy/wallet/ui/theme/modal/ChoosePeriodModal.kt
- app/src/main/java/com/ivy/wallet/ui/theme/modal/edit/ChooseCategoryModal.kt
- app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionCard.kt
- app/src/main/java/com/ivy/wallet/ui/theme/transaction/TransactionSectionDivider.kt
successfully.
- Closes #345
- Fixed font baseline alignment using baseline shift instead of padding workaround.
- Right click
_Note: If you've checked …
> Fixed font baseline alignment using baseline shift instead of padding workaround

- README.md
- Now in TL;DR about contributing it says that it is necessary to submit PRs only to develop branch
> Add a warning about submitting PRs only to develop branch in README

- app/src/main/java/com/ivy/wallet/ui/accounts/AccountsTab.kt
- app/src/main/java/com/ivy/wallet/ui/accounts/IncomeExpensesRow.kt
- app/src/main/java/com/ivy/wallet/ui/balance/BalanceScreen.kt
- app/src/main/java/com/ivy/wallet/ui/bankintegrations/ConnectBankScreen.kt
- app/src/main/java/com/ivy/wallet/ui/budget/BudgetBottomBar.kt
- app/src/main/java/com/ivy/wallet/ui/budget/BudgetScreen.kt
- app/src/main/java/com/ivy/wallet/ui/category/CategoriesBottomBar.kt
- app/src/main/java/com/ivy/wallet/ui/charts/ChartsScreen.kt
- app/src/main/java/com/ivy/wallet/ui/charts/charts/CategoryCharts.kt
- app/src/main/java/com/ivy/wallet/ui/charts/charts/WalletCharts.kt
- app/src/main/res/values/strings.xml
successfully.
- Added strings to the strings.xml file
- Inserted the new strings inside app UI instead of hard-coded strings …
> Replace hard-coded strings in the app UI

- app/src/main/java/com/ivy/wallet/ui/edit/EditTransactionScreen.kt
- app/src/main/java/com/ivy/wallet/ui/loandetails/LoanDetailsScreen.kt
- app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticBottomBar.kt
- app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticScreen.kt
- app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticViewModel.kt
- app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticScreen.kt
- app/src/main/java/com/ivy/wallet/ui/statistic/level2/ItemStatisticViewModel.kt
- app/src/main/res/values/strings.xml
successfully.
- a
- b
- c
- d
- Right click …
> Added strings for ui.statistic and fixed some strings from previous commits

- app/src/main/java/com/ivy/wallet/domain/data/IntervalType.kt
- app/src/main/java/com/ivy/wallet/domain/deprecated/logic/PreloadDataLogic.kt
- app/src/main/java/com/ivy/wallet/utils/DateExt.kt
- app/src/main/res/layout/widget_add_transaction.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
successfully.
- a
- b
- c
- d
- Right click …
> Added hard-coded strings in strings.xml and optimized italian translation

- app/src/main/java/com/ivy/wallet/ui/statistic/level1/PieChartStatisticScreen.kt
- app/src/main/java/com/ivy/wallet/ui/theme/components/ItemIcon.kt
successfully.
- a Icon Size in Piechart Screens are now smaller
- b
- c
- d
- Find `com …
> Fix PieChartScreen IconSize

- app/src/main/java/com/ivy/wallet/ui/planned/list/PlannedPaymentsLazyColumn.kt
- app/src/main/java/com/ivy/wallet/ui/reports/ReportScreen.kt
- app/src/main/java/com/ivy/wallet/ui/search/SearchScreen.kt
- app/src/main/java/com/ivy/wallet/ui/theme/transaction/Transactions.kt
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
successfully.
- a
- b
- c
- d
- Right click …
> Removed hard-coded strings

- .github/workflows/apk.yml
- README.md
successfully.
- a
- b
- c
- d
- Right click …
> Fix the prod readme

- app/src/main/java/com/ivy/wallet/backup/github/GitHubAutoBackupManager.kt
- app/src/main/java/com/ivy/wallet/backup/github/GitHubBackup.kt
- app/src/main/java/com/ivy/wallet/backup/github/GitHubClient.kt
- app/src/main/java/com/ivy/wallet/backup/github/GitHubCredentials.kt
- app/src/main/java/com/ivy/wallet/backup/github/GitHubCredentialsManager.kt
- app/src/main/java/com/ivy/wallet/backup/github/ui/GitHubBackupCard.kt
- app/src/main/java/com/ivy/wallet/backup/github/ui/GitHubBackupScreen.kt
- app/src/main/java/com/ivy/wallet/backup/github/ui/GitHubBackupStatus.kt
- app/src/main/java/com/ivy/wallet/backup/github/ui/GitHubBackupViewModel.kt
- app/src/main/java/com/ivy/wallet/backup/github/ui/GitHubBackupViewState.kt
- app/src/main/java/com/ivy/wallet/backup/ktor/KtorClient.kt
- app/src/main/java/com/ivy/wallet/domain/deprecated/logic/zip/BackupLogic.kt
- app/src/main/java/com/ivy/wallet/domain/deprecated/logic/zip/ExportBackupLogic.kt
- app/src/main/java/com/ivy/wallet/ui/csvimport/ImportViewModel.kt
- app/src/main/java/com/ivy/wallet/ui/serverstop/ServerStopViewModel.kt
- app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
successfully.
- a
- b
- c
- d
- Right click …
> GitHub backups

- app/src/main/java/com/ivy/wallet/domain/deprecated/logic/csv/ExportCSVLogic.kt
**[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md)**.
_Put an `x` in all the boxes that apply._
- Closes #520 
- the values are getting now handled depending on the localDecimalSeparator
- result format in any device language should be "1078.95"
> Fix Issue 520

- .github/workflows/upgrade-gradle-wrapper.yml
- build.gradle.kts
- gradle/libs.versions.toml
> Upload a screen recording + screenshots to prove that your changes work.
Please check the type of the changes that your PR introduce:
Put an `x` in all the boxes that apply.
- Added a new Gradle plugin that can be used to upgrade the Gradle Wrapper (and create an PR if so)
- Added a GitHub Action workflow that will run periodically to check if there is an Wrapper upgrade
- 
_💡 Tip: Attach screenshots and screen recordings. It helps a lot!_
- Closes #2449 
Test your build again with …
> Automate gradle wrapper upgrade

- README.md
Added the contribution details of GitHub Backup Feature Tutorial by ADX [ＫＬムＵＳ] as asked.
> Updated Contribution of Tutorial by ADX.

- app/src/main/java/com/ivy/wallet/ui/settings/SettingsScreen.kt
- app/src/main/java/com/ivy/wallet/ui/settings/SettingsViewModel.kt
- There's a switch theme button in Settings screen as well which gives you the possibility to pick between Auto/Light/Dark mode.
Auto | Light | Dark
--- | --- | ---
- Closes #2581
> Fix issue 2581 - Change theme button in settings

- .github/workflows/upgrade-gradle-wrapper.yml
Lets go with this for now 🤓 
I will not run tests, but you get at least informed about it via PRs.
A simple `checkout PR_number` and `./gradlew check` or something should reveal if it works or not 😉 
Better than nothing I would say.
Your token can also be updated later, in case this apporoach is getting too annoying. But I doubt it, because Gradle reelase are also not *that often* 🙃
> Fix Gradle Wrapper Uprade (again)

- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/BalanceRow.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/utils/AmountFormatting.kt
Obtaining the integer part of balance via `toInt()` method drops the negative sign when the balance x is such that  -1.0 < x < 0.0. For example, (-0.21).toInt() will produce 0.
This PR will append a negative sign to the integer part of the balance in this case.
https://github.com/Ivy-Apps/ivy-wallet/assets/12750237/96e52e8c-fab3-4201-b2b7-3f3409b1e5ab
https://github.com/Ivy-Apps/ivy-wallet/assets/12750237/80fe36d7-34e3-4c94-abdd-8e739b3bf495
- Closes [2518](https://github.com/Ivy-Apps/ivy-wallet/issues/2518)
> Fix negative zero issue on balance

- screen-balance/src/main/java/com/ivy/balance/BalanceEvent.kt
- screen-balance/src/main/java/com/ivy/balance/BalanceScreen.kt
- screen-balance/src/main/java/com/ivy/balance/BalanceState.kt
- screen-balance/src/main/java/com/ivy/balance/BalanceViewModel.kt
[Screen_recording_20231022_152042.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/20263744/6c825191-7275-474f-a2fa-2bce4f9e9fc8)
- Closes #2620 
If you see any of the PR checks failing (❌) go to …
> refs #2620: Migrate screen-balance to ComposeViewModel

- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/CircleButtons.kt
- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …
> Fix detekt warnings 2810

- ivy-resources/src/main/res/values-ar/strings.xml
- ivy-resources/src/main/res/values-bg/strings.xml
- ivy-resources/src/main/res/values-es/strings.xml
- ivy-resources/src/main/res/values-hi/strings.xml
- ivy-resources/src/main/res/values-it/strings.xml
- ivy-resources/src/main/res/values-kn/strings.xml
- ivy-resources/src/main/res/values-mn/strings.xml
- ivy-resources/src/main/res/values-ru/strings.xml
- ivy-resources/src/main/res/values/strings.xml
- screen-accounts/src/main/java/com/ivy/accounts/AccountsState.kt
- screen-accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen-accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
- screen-balance/src/main/java/com/ivy/balance/BalanceViewModel.kt
https://github.com/Ivy-Apps/ivy-wallet/assets/68247763/ad6c8e00-ae88-472f-b32a-95b907e8d56d
- As discussed in #2811 , i added a second label to easily distinguish between the total of all accounts and the exclusive total.
- Translations might not be perfect
- It should work in every case
- #2811 is already closed
> Replace `ISSUE_NUMBER` with your issue number (for example Closes #1234). If …
> Money total sum customization

- screen-accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen-balance/src/main/java/com/ivy/balance/BalanceScreen.kt
- screen-categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
- screen-home/src/main/java/com/ivy/home/HomeHeader.kt
- screen-loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/BalanceRow.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/IvyModalDomainComponents.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/EditBottomSheet.kt
Idk... made another attempt at this thing. If this one doesn't work, I'll prooly give up on it, as making it made me refactor a lot of other things to not get weird warnings. I hope it passes these tests so we can have these lines look like they should.
https://github.com/Ivy-Apps/ivy-wallet/pull/2821
> Balance row enhancement, attempt #2

- screen-planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedScreen.kt
- screen-planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedScreenEvent.kt
- screen-planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedViewModel.kt
- Fixed: On edit of category name from add planned payment screen, the name will be changed.
https://github.com/Ivy-Apps/ivy-wallet/assets/53510640/bf64436c-4b65-4bd6-95c1-68bb94314b9d
- Closes #2855 
If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed check and explore the logs to see why it has failed.
[Detekt](https://detekt.dev/) is a static code analyzer for Kotlin that we use to enforce code …
> refs #2855 - Edit category name from add planned payment screen 

- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/IvyTitleTextField.kt
[Screen_recording_20240119_162547.webm](https://github.com/Ivy-Apps/ivy-wallet/assets/76241334/7f6a134f-dd6b-437e-a2e3-b7ee3037bc41)
- Tapping on the empty space adjacent to "Expense title" now bring the text box to focus
Closes #2877
> Fixed: Tapping on "Expense title" textbox does not request focus

- screen-home/src/main/java/com/ivy/home/HomeHeader.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/data/model/TimePeriod.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/BalanceRow.kt
- temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/wallet/AmountCurrency.kt
Before | After
---|---
- made stickyheader balance display in two rows
- restored 4 asterisks on hidden balance rows
- abbreviate months in stickyheader when displayed next to a year to make it shorter (not shown in comparison)
It probably won't work for everyone in every case, but this way we get a better handle on the sticky header.
- Closes #2880
I'm sure this lint shit will prevent us from merging it directly, but let's try.. :D
> Stickyheader overlap fixes

- .github/workflows/integration_test.yml
- .gitignore
- app/src/main/AndroidManifest.xml
- app/src/main/res/values/styles.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/ivy.room.gradle.kts
- gradle/libs.versions.toml
- ivy-data/build.gradle.kts
- ivy-data/src/androidTest/java/com/ivy/data/db/IvyRoomDatabaseMigrationTest.kt
- ivy-data/src/main/java/com/ivy/data/db/IvyRoomDatabase.kt
- ivy-resources/build.gradle.kts
- a
- b
- c
- d
- a
- b
- c
- a
- b
- c …
> Integration tests

- screen/home/src/main/java/com/ivy/home/HomeViewModel.kt
- screen/settings/src/main/java/com/ivy/settings/SettingsViewModel.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/settings/SettingsAct.kt
- Implemented getSettingsWithNextTheme function in SettingsAct. Thanks to this change, codebase is a bit more DRY.
- Refactored SettingsViewModel and HomeViewModel to use this function when changing the theme.
- Changed `theme` in HomeViewModel to `currentTheme` to ensure consistency of naming in SettingsViewModel and HomeViewModel
https://github.com/Ivy-Apps/ivy-wallet/assets/70368829/9d61c4bb-5206-485c-b08d-f6edc7e5b687
- None I guess
- Closes #2939 
> Fix-Issue-2939

- README.md
**Previous**
**Now**
- Image load in read me changed to new images and URL changed to correct ones which does exists.
- Closes #2946
> Fix issue 2946

- screen/categories/src/main/java/com/ivy/categories/CategoriesViewModel.kt
While sorting with balance amount the negative and positive balance are sorted with absolute value. So, I changed it with normal sorting and all the balance with 0 value are appended to the end.
Before | After
--|--
image1 | image2
-->
Before
After 
-  remove .absoluteValue and added partition to add all 0 value balance in the end.
No risk factors.
- Closes #2940  …
> fix-issue-2940

- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/CalculatorModal.kt
Changed button characters for multiplication and subtraction operators to match those used in the general calculator layout. Previously used "x" and "-" looked bad in the expression line.
https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/d68ea786-7fce-4946-87c2-7ce4eecaf139
> More accurate characters for some calculator buttons

- screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
- screen/settings/src/main/java/com/ivy/settings/SettingsViewModel.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/utils/DateExt.kt
Unfortunately [this](https://github.com/Ivy-Apps/ivy-wallet/commit/b04e918e00f0e9aae69608242ce42e69fd6d7a27) commit reverted all of the https://github.com/Ivy-Apps/ivy-wallet/pull/3012 efforts. This PR brings it back and fixes a problem with the `:` character, which is not handled correctly by certain operating systems.
> Restore ISO 8601 date formatting for exported files

- screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
- screen/transactions/src/main/java/com/ivy/transactions/TransactionsScreen.kt
Before | After
--|--
I fixed the alignment of <(excluded)> strings on Accounts, Loans and Transactions screens.
Not sure how it looks like on smaller screens.
> Fix alignment of the exclusion string

- temp/legacy-code/src/main/java/com/ivy/legacy/domain/pure/transaction/AccountValueFunctions.kt
- a This fixes In correct Account Transfer that was happening (this isn't a rework)
- b
- c
- a
- b
- a
- b
- Closes #2910 
> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue …
> [IVY-2910] Fix Incorrect Balance Transfer

- README.md
- shared/resources/src/main/res/values/strings.xml
Fixed some typos and rephrased multiple strings.
> Some readme.md improvements

- screen/home/src/main/java/com/ivy/home/customerjourney/CustomerJourney.kt
- shared/ui/core/src/main/res/values-vi/strings.xml
- temp/legacy-code/src/main/java/com/ivy/legacy/utils/AmountFormatting.kt
- widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt
Root cause: 
-> The error is when we put the number in short form and someone when parsing to double does not handle that case so it causes an error
Before
| After
https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/cafa329a-a5a3-48f1-8f11-3f7f3f008738
- Add function to convert string to number for calculation
- Fix typo in Vietnamese translation
- Fix padding in cardjourney at homeTab
No
- Closes #3106
> Fix issue 3106

- temp/legacy-code/src/main/java/com/ivy/legacy/utils/AmountFormatting.kt
The value in app
Before
After
I discovered that the toCalcBalanceAmount function I handled last time was not handled correctly
example balance is 10.03k -> it will convert to 10.03000 = 10.03 -> it's wrong balance
it should be 10380 and display in the widget 10.03k
Before
No risk
> update function toCalcBalanceAmount to make the right value

- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt
+ Fix the initial amount from "0" to ""
+ Adjust padding betwwen number pad
| Before    | After |
| -------- | ------- |
|https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/da0f1b68-5c31-4511-9893-34acfeb66248|https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/f5dac40b-e8e6-4c16-9bb1-a581be9cf26d|
No risk factors
- Closes #3105
- Closes #3108
> Fix error initial amount in calculatorModal, adjust padding amount keyboard

- shared/ui/core/src/main/res/drawable/ic_launcher_foreground.xml
Fixed Issue #3181 
i have adjust the ic_launcher_foreground so that it shows the the quick settings tile perfectly.
> Fixes issue #3181 Quick Settings Tile Small Icon

- CONTRIBUTING.md
- [✅] The PR is submitted to the `main` branch.
- [✅] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [✅] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [✅] I confirm that I've run the code locally and everything works as expected.
- [✅] 🎬 I've attached a **screen recoding** of the changes.
- [✅] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
Before:
After:
- Texts were made simpler and easier to read
- I've deleted some of the more …
> Issue 3270 - CONTRIBUTING.md fixes and readability enhancements

- .github/PULL_REQUEST_TEMPLATE.md
- [✅] The PR is submitted to the `main` branch.
- [✅] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [✅] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [✅] I confirm that I've run the code locally and everything works as expected.
- [✅] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
Before| After
---------|---------
- Changed proposed way of ticking checkboxes (to the way I did it here above) - more stands out especially in the dark …
> PR template readability and standardization fixes

- temp/legacy-code/src/main/java/com/ivy/legacy/domain/data/IvyCurrency.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/CustomExchangeRateCard.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/EditBottomSheet.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/TransactionCard.kt
- Updated to use different decimal place for crypto and fiat currency
|Before|After|
:------:|:-----:
- Exchange rate wrapping may happen for small screen
- ...
- ...
- Closes #3287 
> Different decimal place for crypto and fiat currency

- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt
- Dynamic decimal place for amount input sheet
- 2 decimal for fiat currency
- 18 decimal for crypto
Before|After
-------|-------
- There will be wrapping for crypto exchange rates on small screens
- ...
- Closes #3287 
> fixes decimal place in amount input sheet

- app/build.gradle.kts
- app/src/main/java/com/ivy/IvyNavGraph.kt
- app/src/main/java/com/ivy/wallet/RootActivity.kt
- app/src/main/java/com/ivy/wallet/RootViewModel.kt
- app/src/main/java/com/ivy/wallet/migrations/MigrationsManager.kt
- app/src/main/java/com/ivy/wallet/ui/applocked/AppLockedScreen.kt
- config/detekt/baseline.yml
- config/detekt/config.yml
- gradle/libs.versions.toml
- screen/onboarding/src/main/java/com/ivy/onboarding/OnboardingEvent.kt
- screen/onboarding/src/main/java/com/ivy/onboarding/steps/OnboardingSplashLogin.kt
- screen/onboarding/src/main/java/com/ivy/onboarding/viewmodel/OnboardingViewModel.kt
…ts and files.
- ...
- ...
- ...
- ...
- ...
- ...
- Closes #3314
> Removed all code related to sign in through google from app.

- gradle/libs.versions.toml
- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionEvent.kt
- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionScreen.kt
- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
- screen/planned-payments/src/main/java/com/ivy/planned/edit/EditPlannedScreen.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/Toolbar.kt
[Screen_recording_20240717_003727.webm](https://github.com/user-attachments/assets/64cafe13-ccf2-480a-ae3d-cef4f9e457ae)
- add material-icons-extended library
- add duplicate button to the edit transaction screen
- use icon from material-icons-extended to maintain consistency with the material style
- duplicate transaction on clicking the duplicate button and close the transaction screen
- don't show the duplicate button for editing planned payments (that doesn't make any sense)
I've tested the new code locally on real device and emulator, with both themes and for both expenses and incomes. However, I was not able to test the duplication of transfers because they are broken now. 
- Closes #3342
Pull request checks …
> Fix issue 3342

- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/CalculatorModal.kt
Resolved an issue in the CalculatorModal where consecutive operators could be added, resulting in invalid expressions.
- Updated the handleOperator function to ensure only one operator is added at a time.
- Replaced the last operator if a new operator is pressed.
- Ensured the input behaves like a standard calculator.
This change improves the user experience by preventing invalid expressions and aligning the calculator's behavior with user expectations.
Before
https://github.com/user-attachments/assets/c4cb087d-e360-44b1-90fd-38f3436e5e04
After:
https://github.com/user-attachments/assets/085816dc-9ad7-459a-b48e-c35e3bd649ad
> Fix: Prevent consecutive operator input in CalculatorModal

- screen/budgets/src/main/java/com/ivy/budgets/BudgetScreen.kt
- screen/budgets/src/main/java/com/ivy/budgets/BudgetScreenState.kt
- screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
- shared/ui/core/src/main/res/values-ar/strings.xml
- shared/ui/core/src/main/res/values-bg/strings.xml
- shared/ui/core/src/main/res/values-de/strings.xml
- shared/ui/core/src/main/res/values-es/strings.xml
- shared/ui/core/src/main/res/values-hi/strings.xml
- shared/ui/core/src/main/res/values-id/strings.xml
- shared/ui/core/src/main/res/values-in/strings.xml
- shared/ui/core/src/main/res/values-it/strings.xml
- shared/ui/core/src/main/res/values-kn/strings.xml
- shared/ui/core/src/main/res/values-mn/strings.xml
- shared/ui/core/src/main/res/values-pl/strings.xml
- shared/ui/core/src/main/res/values-pt-rBR/strings.xml
- shared/ui/core/src/main/res/values-ru/strings.xml
- shared/ui/core/src/main/res/values-vi/strings.xml
- shared/ui/core/src/main/res/values-zh-rCN/strings.xml
- shared/ui/core/src/main/res/values-zh-rTW/strings.xml
- shared/ui/core/src/main/res/values/strings.xml
https://github.com/user-attachments/assets/b2ad6d2b-a159-4f51-ba60-80ce8fa4c500
- Added display for "Total Remaining Budget" beneath budget information. 
- Calculated remaining budget for categorized and multi-categorized budgets.
- Included multi-language support for the "Total Remaining Budget" text. 
- Enhanced user experience by providing a clear overview of remaining budget without manual summarization.
- Closes #3365
> feat: Add "Total Remaining Budget" display

- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/IntervalPickerRow.kt
- Set a maximum text length of three digits for the interval input field.
- Adjusted the button width to ensure it stays perfectly within the screen.
- Applied the logic that the maximum interval can only be up to 365 days, which fits within three digits.
Before
https://github.com/user-attachments/assets/25168f98-4892-4df5-ac43-5d6673082618
After
https://github.com/user-attachments/assets/5dcb4e8a-0262-489d-8d46-4ba597e360db
- Closes #3349
> Implement maximum text length constraint for interval input field

- screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
- screen/home/src/main/java/com/ivy/home/HomeViewModel.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/data/model/FromToTimeRange.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/transaction/HistoryDateDivider.kt
https://github.com/user-attachments/assets/8749b4eb-5c81-4544-8c27-26a9d9ddfd0d
- Fixed timstamp for transactions for which user were relying on default selection
- Fixed transactions fetch range
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3327 
> fixed invalid timestamp for transactions with unedited date or time

- .github/workflows/apk.yml
- .github/workflows/ci_actions_test.yml
- .github/workflows/compose_stability.yml
- .github/workflows/detekt.yml
- .github/workflows/integration_test.yml
- .github/workflows/internal_release.yml
- .github/workflows/issue_assign.yml
- .github/workflows/issue_created.yml
- .github/workflows/lint.yml
- .github/workflows/paparazzi_screenshot_test.yml
- .github/workflows/pr_description.yml
- .github/workflows/test.yml
- I've fixed the "Integration tests" GitHub Actions workflow.
- Makes all GitHub Actions workflow use the standard `gradle/actions/setup-gradle@v4`
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3391 
> Fix Integration tests

- shared/domain/src/main/java/com/ivy/domain/usecase/BalanceBuilder.kt
- shared/domain/src/main/java/com/ivy/domain/usecase/account/AccountBalanceUseCase.kt
- shared/domain/src/test/java/com/ivy/domain/usecase/balance/BalanceBuilderTest.kt
- I've implemented the methods of AccountBalanceUseCase
- Closes #3143
> [Domain] Build AccountBalanceUseCase

- temp/legacy-code/src/main/java/com/ivy/legacy/data/model/FromToTimeRange.kt
- I've fixed crash  `App crashes when viewing expanded categories in expense or income section`
- No known case
- No known case
- Closes #3440 
> Fix of [BUG] App crashes when viewing expanded categories in expense or income section

- screen/accounts/src/main/java/com/ivy/accounts/AccountsState.kt
- screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
- screen/accounts/src/main/java/com/ivy/accounts/IncomeExpensesRow.kt
- shared/domain/src/main/java/com/ivy/domain/features/Features.kt
- shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
- [ x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ x] I confirm that I've run the code locally and everything works as expected.
- [ x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [ x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).
[recording](https://github.com/user-attachments/assets/a56e063e-4e66-48bd-b714-4aa9b9e76b06) …
> [FEATURE] Setting to hide balances from the "Accounts" tab

- screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
- I've fixed [BUG] Updating a transaction from a report does not get reflected 
-  No know case
- No know case
- Closes #3438 
> fix-issue-3438

- app/src/main/java/com/ivy/wallet/RootActivity.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenEvent.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoanScreenState.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
- screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt
- screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreenState.kt
- screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt
- screen/loans/src/main/java/com/ivy/loans/loandetails/events/LoanModalEvent.kt
- screen/loans/src/main/java/com/ivy/loans/loandetails/events/LoanRecordModalEvent.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt
https://github.com/user-attachments/assets/349091c1-3b90-4aea-931b-1f55376d3bfe
used the new Time Provider APIs 
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3481
> fix-issue-3481

- shared/ui/navigation/src/main/java/com/ivy/navigation/Screens.kt
- When we go to `transaction details screen`  from` transaction list screen` , upon coming back, we loose scroll position. It happens because screens where `isLegacy ` is not true, their viewModel gets cleared as soon as corresponding composable is left out of the screen.
- Closes #3455 
> fix-issue-3455

- screen/piechart/src/main/java/com/ivy/piechart/PieChartStatisticScreen.kt
Pie Chart Screen Scroll Position Lost bug fixed
Before|After
---|---
https://github.com/user-attachments/assets/5c7ecace-511c-4458-b59b-6fca96647f13|https://github.com/user-attachments/assets/116ff4d8-4a7a-49a5-aa94-6b8e3c7c2b20
- Closes #3492 
> Fix issue 3492

- screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
Refactoring done for EditTransactionViewModel interms of` Use of Delegate of MutableState`
- Closes #3506 
> EditTransactionViewModel-> Use of Delegate of MutableState

- .idea/inspectionProfiles/Project_Default.xml
- screen/home/src/main/java/com/ivy/home/HomeViewModel.kt
- I've fixed...
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3505
> Refactor: Use 'by' delegation for mutableStateOf properties

- screen/loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt
- I've updated LoanViewModel  as such that all its mutableStates uses by delegate
- N/A
- N/A
- Closes #3522 
> [Refactor] LoanViewModel : using by delegation for mutable states

- screen/balance/src/main/java/com/ivy/balance/BalanceViewModel.kt
- I've updated BalanceViewModel as such that all its mutableStates uses by delegation
- N/A
- N/A
- Closes #3521 
> [Refactor] BalanceViewModel: using by delegation for mutable states

- screen/accounts/src/main/java/com/ivy/accounts/AccountsViewModel.kt
- I've updated AccountsViewModel as such that all it's mutableStates uses by delegate
- N/A
- N/A
- Closes #3520 
> [Refactor] AccountsViewModel: using by delegation for mutable states

- screen/planned-payments/src/main/java/com/ivy/planned/list/PlannedPaymentsViewModel.kt
- I've updated PlannedPaymentsViewModel such that all it's mutableStates uses by delegate
- N/A
- N/A
- Closes #3528 
> [Refactor] PlannedPaymentsViewModel: using by delegation for mutable states

- screen/reports/src/main/java/com/ivy/reports/ReportViewModel.kt
- I've updated ReportViewModel such that all it's mutableStates uses by delegates
- N/A
- N/A
- Closes #3527 
> [Refactor] ReportViewModel: using by delegation for mutable states

- screen/piechart/src/main/java/com/ivy/piechart/PieChartStatisticViewModel.kt
- I've updated PieChartStatisticViewModel such that all it's mutableStates uses by delegates
- N/A
- N/A
- Closes #3526 
> [Refactor] PieChartStatisticViewModel: using by delegation for mutable states

- screen/features/build.gradle.kts
- screen/features/src/main/java/com/ivy/features/FeaturesScreen.kt
- screen/features/src/main/java/com/ivy/features/FeaturesUiEvent.kt
- screen/features/src/main/java/com/ivy/features/FeaturesUiState.kt
- screen/features/src/main/java/com/ivy/features/FeaturesViewModel.kt
- shared/domain/src/main/java/com/ivy/domain/features/BoolFeature.kt
- shared/domain/src/main/java/com/ivy/domain/features/FeatureGroup.kt
- shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
- I've included advanced feature grouping.
- N/A
- N/A
- Closes #3559
> [FEATURE] Advanced features grouping

- temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/viewmodel/home/DueTrnsInfoAct.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/RecurringRuleModal.kt
No
Assume that on September 29, 2024, we create a recurring expense named **`MyRecurrentExpense`**. Consequently, an entry for **`MyRecurrentExpense`** appears in the **`upcoming section`** of the home screen for September 29. Previously, this entry was moved to the **`overdue section`** at 12:00 AM UTC rather than 12:00 AM local time. Now, the entry is moved to the **`overdue section`** at 12:00 AM local time.
**N.B:** Expenses from September 29 will move to the **`overdue section`** on September 30 at 12:00 AM local time.
No
No
- Closes N/A
> Fix #3432 Recurring expenses spawn at UTC timing instead of local time

- screen/accounts/src/main/java/com/ivy/accounts/AccountsTab.kt
- screen/accounts/src/main/java/com/ivy/accounts/IncomeExpensesRow.kt
- screen/home/src/main/java/com/ivy/home/HomeHeader.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/wallet/AmountCurrency.kt
- I've added the capability to hide total Balance Section in Accounts Tab.
- Added missing `supressLint ` annotation in relevant pages.
https://github.com/user-attachments/assets/e19a66ed-3d70-496a-8313-3d635d4d6ec1
-N/A
-N/A
- Closes #3597 
> [Feature] Hide Total Income When Corresponding Toggle Is Off

- screen/loans/src/main/java/com/ivy/loans/loan/Constants.kt
- screen/loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt
https://github.com/user-attachments/assets/32df4db7-7579-41cf-a0bc-8ba5ee1042bd
- I've added horizontal swipe support to the loan screen just like the home screen
Before|After
---|---
No horizontal swipe|Horizontal swipe ✅
- These changes aren't dangerous.
- Closes #3589
> Add horizontal swipe gesture to loans screen

- shared/domain/src/main/java/com/ivy/domain/di/IvyCoreBindingsModule.kt
- shared/domain/src/main/java/com/ivy/domain/features/Features.kt
- shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
- temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt
https://github.com/user-attachments/assets/32b0f1ef-c86f-4631-a81a-07284d269bd1
We just had the calculator like numeric pad in the keypad or the `AmountKeyboard`. No you can toggle the setting in settings and switch between standard and numeric style keypad.
- I've added setting to toggle keypad layout between numeric & standard
- Not a dangerous feature.
- Code wise, adding the state directly inside the composable might be an anti pattern but its fine for a simple static composable.
- The setting is only togglable from the settings so frequent recompositions isn't a issue when the keyboard is already drawn on screen.
- This way,`AmountKeyboard` is self-contained, making it …
> Add setting to toggle keypad layout between numeric & standard

- screen/transactions/src/main/java/com/ivy/transactions/TransactionsScreen.kt
https://github.com/user-attachments/assets/37c9f8cc-bad9-4784-bf18-bf5baa95a7ec
The dialog doesn't reappear now
- I've fixed dialog visibility state not reset after confirm deletion of account
- N/A
- N/A
- Closes #3616
> Fix deletion dialog incorrectly reappearing bug

- screen/exchange-rates/src/main/java/com/ivy/exchangerates/modal/AddRateModal.kt
[Add currency.webm](https://github.com/user-attachments/assets/5a76506d-8bcd-4b41-823b-ab65fb268b4e)
- I've fixed...
Before|After
---|---
- ...
- ...
- ...
- ...
- Closes #3624 
> Change currency textfield design

- shared/domain/src/main/java/com/ivy/domain/features/BoolFeature.kt
- shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
- I've fixed added missing default values for Ivy Features.
- N/A
- N/A
- Closes #3630 
> [BUG] Added Missing default values for IvyFeatures

- shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
- improved descriptions for several ivyfeatures
- Closes N/A
> Description fixes and rephrasals for ivyfeatures

- shared/ui/core/src/main/res/values-es/strings.xml
- Please take a look to the screenshots at "Before|After" section.
- I've added the missing translations to Spanish of some labels and descriptions at the Settings screen.
Before|After
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
- Nothing
- It won't work if the `switchLanguage()` function from the SettingsViewModel is deleted.
- Closes #3654
> Add missing spanish labels and descriptions at settings screen
